# ═══════════════════════════════════════════════════════════════════
#  01 — Create Native Auth App Registration
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Create the application registration in your External ID
#           tenant for native auth (email + password sign-up/sign-in).
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  Before running: edit the CONFIG block below for your tenant.
#  Chains to:      02-create-user-flow.ps1 via .last-created-app.json
#
#  Run: pwsh ./01-create-native-app.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── CONFIG (edit these for your tenant) ───
$tenantId    = "{{TENANT_ID}}"
$appName     = "{{APP_NAME}}"
$bundleId    = "{{BUNDLE_ID}}"

# ─── CONNECT ───
Write-Host "`n[1/3] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    $context = Get-MgContext
    if (-not $context -or $context.TenantId -ne $tenantId) {
        Connect-MgGraph -TenantId $tenantId -Scopes "Application.ReadWrite.All" -NoWelcome -ErrorAction Stop
        $context = Get-MgContext
    }
    if (-not $context -or $context.TenantId -ne $tenantId) {
        throw "Not connected to tenant '$tenantId' (current: '$($context.TenantId)'). Sign in with an account in that tenant, or fix the `$tenantId value in the CONFIG block above."
    }
    Write-Host "  Connected to tenant: $($context.TenantId)" -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  Make sure Microsoft.Graph PowerShell SDK is installed:" -ForegroundColor Yellow
    Write-Host "    Install-Module Microsoft.Graph -Scope CurrentUser" -ForegroundColor Yellow
    exit 1
}

# ─── BUILD REQUEST BODY ───
Write-Host "`n[2/3] Building app registration request..." -ForegroundColor Cyan
$body = @{
    displayName            = $appName
    signInAudience         = "AzureADMyOrg"
    isFallbackPublicClient = $true
    publicClient = @{
        redirectUris = @("msauth://$bundleId/callback")
    }
    nativeAuthenticationApisEnabled = "all"
    api = @{
        requestedAccessTokenVersion = 2
    }
    requiredResourceAccess = @(
        @{
            resourceAppId = "00000003-0000-0000-c000-000000000000"  # Microsoft Graph
            resourceAccess = @(
                @{ id = "37f7f235-527c-4136-accd-4a02d197296e"; type = "Scope" }   # openid
                @{ id = "7427e0e9-2fba-42fe-b0c0-848c9e6a8182"; type = "Scope" }   # offline_access
                @{ id = "14dad69e-099b-42c9-810b-d002981feec1"; type = "Scope" }   # profile
            )
        }
    )
} | ConvertTo-Json -Depth 10

Write-Host "  Request body:" -ForegroundColor Cyan
Write-Host $body -ForegroundColor Gray

# ─── CALL GRAPH API (idempotent: reuse the app if it already exists) ───
Write-Host "`n[3/3] Creating app registration via POST /v1.0/applications..." -ForegroundColor Cyan
try {
    $escapedName = $appName.Replace("'", "''")
    $existing = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/applications?`$filter=displayName eq '$escapedName'&`$select=id,appId,displayName,createdDateTime,isFallbackPublicClient,nativeAuthenticationApisEnabled,publicClient,api,requiredResourceAccess"

    if ($existing.value -and @($existing.value).Count -gt 0) {
        $app = @($existing.value)[0]
        $manifestIssues = @()
        if ($app.isFallbackPublicClient -ne $true) { $manifestIssues += "isFallbackPublicClient is not true" }
        if ($app.nativeAuthenticationApisEnabled -ne "all") { $manifestIssues += "nativeAuthenticationApisEnabled is not 'all'" }
        if (@($app.publicClient.redirectUris) -notcontains "msauth://$bundleId/callback") { $manifestIssues += "required msauth redirect URI is missing" }
        if ($app.api.requestedAccessTokenVersion -ne 2) { $manifestIssues += "requestedAccessTokenVersion is not 2" }
        $graphAccess = @($app.requiredResourceAccess | Where-Object { $_.resourceAppId -eq "00000003-0000-0000-c000-000000000000" }).resourceAccess
        foreach ($scopeId in @(
            "37f7f235-527c-4136-accd-4a02d197296e",
            "7427e0e9-2fba-42fe-b0c0-848c9e6a8182",
            "14dad69e-099b-42c9-810b-d002981feec1"
        )) {
            if (@($graphAccess.id) -notcontains $scopeId) { $manifestIssues += "required Microsoft Graph scope $scopeId is missing" }
        }
        if ($manifestIssues.Count -gt 0) {
            Write-Host "`n  Existing same-name app is not safe to reuse:" -ForegroundColor Red
            foreach ($issue in $manifestIssues) { Write-Host "    - $issue" -ForegroundColor Red }
            Write-Host "  Fix its manifest or choose a unique `$appName, then re-run. No app was modified." -ForegroundColor Yellow
            exit 1
        }
        Write-Host "`n  FOUND existing app '$appName' - reusing it (no duplicate created)" -ForegroundColor Yellow
    } else {
        $app = Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/applications" `
            -Body $body `
            -ContentType "application/json"
        Write-Host "`n  SUCCESS - App created!" -ForegroundColor Green
    }
    Write-Host "  ---------------------------------------" -ForegroundColor Green
    Write-Host "  Display Name : $($app.displayName)" -ForegroundColor White
    Write-Host "  App ID       : $($app.appId)" -ForegroundColor White
    Write-Host "  Object ID    : $($app.id)" -ForegroundColor White
    Write-Host "  Created      : $($app.createdDateTime)" -ForegroundColor White
    Write-Host "  ---------------------------------------" -ForegroundColor Green

    # Save for next scripts
    $createdAppContext = @{
        appId    = $app.appId
        objectId = $app.id
        tenantId = $tenantId
    }
    $createdAppContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-created-app.json"
    Write-Host "`n  Saved app context to .last-created-app.json (for next scripts)" -ForegroundColor Cyan

    # ─── ENSURE SERVICE PRINCIPAL (idempotent: required to bind app to a user flow) ───
    Write-Host "`n[4/4] Ensuring service principal for the app..." -ForegroundColor Cyan
    try {
        $spExisting = Invoke-MgGraphRequest `
            -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/servicePrincipals?`$filter=appId eq '$($app.appId)'&`$select=id"
        if ($spExisting.value -and @($spExisting.value).Count -gt 0) {
            $sp = @($spExisting.value)[0]
            Write-Host "  SP already exists: $($sp.id)" -ForegroundColor Yellow
        } else {
            $spBody = @{ appId = $app.appId } | ConvertTo-Json
            $sp = Invoke-MgGraphRequest `
                -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/servicePrincipals" `
                -Body $spBody `
                -ContentType "application/json"
            Write-Host "  SP Object ID : $($sp.id)" -ForegroundColor White
        }

        # Update saved context with SP id
        $createdAppContext.servicePrincipalId = $sp.id
        $createdAppContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-created-app.json"
    } catch {
        Write-Host "  FAILED - service principal creation failed: $($_.Exception.Message)" -ForegroundColor Red
        Write-Host "  The app exists, but the migration cannot continue until its service principal exists." -ForegroundColor Yellow
        Write-Host "  Re-run this script, or create the SP manually:" -ForegroundColor Yellow
        Write-Host "    POST https://graph.microsoft.com/v1.0/servicePrincipals  body: { appId: '$($app.appId)' }" -ForegroundColor Yellow
        exit 1
    }

    Write-Host "`nNEXT STEPS:" -ForegroundColor Yellow
    Write-Host "  1. Go to Entra admin center -> App registrations" -ForegroundColor White
    Write-Host "  2. Verify '$appName' appears with App ID: $($app.appId)" -ForegroundColor White
    Write-Host "  3. Open the Manifest - confirm:" -ForegroundColor White
    Write-Host "     - isFallbackPublicClient: true" -ForegroundColor Gray
    Write-Host "     - nativeAuthenticationApisEnabled: 'all'" -ForegroundColor Gray
    Write-Host "     - publicClient.redirectUris includes msauth URI" -ForegroundColor Gray
    Write-Host "  4. {{NEXT_STEP}}" -ForegroundColor White

} catch {
    Write-Host "`n  FAILED - see error below" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host "`n  Common fixes:" -ForegroundColor Yellow
    Write-Host "  - Re-run Connect-MgGraph with correct scopes" -ForegroundColor Yellow
    Write-Host "  - Check tenant ID is right" -ForegroundColor Yellow
    Write-Host "  - Confirm your account has Application.ReadWrite.All in this tenant" -ForegroundColor Yellow
    exit 1
}
