# ═══════════════════════════════════════════════════════════════════
#  02 — Create Native Auth User Flow (Email + Password sign-up/sign-in)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Create an External ID customer self-service sign-up
#           user flow with the built-in EmailPassword IdP, scoped
#           to the app registration created by script 01.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  Covers Analyzer features:
#    - signUp_auth_emailPassword
#    - signIn_auth_emailPassword
#  Native auth endpoints (/initiate, /challenge, /continue, /token)
#  become available against this flow once the app is bound via
#  conditions.applications.includeApplications.
#
#  Chains from: .last-created-app.json (produced by 01)
#  Produces:    .last-created-flow.json (for 03)
#
#  Run: pwsh ./02-create-user-flow.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/6] Reading context from script 01..." -ForegroundColor Cyan
$contextPath = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $contextPath)) {
    Write-Host "  Missing $contextPath" -ForegroundColor Red
    Write-Host "  Run 01-create-native-app.ps1 first." -ForegroundColor Yellow
    exit 1
}
$appContext = Get-Content $contextPath -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$appId    = $appContext.appId
$objectId = $appContext.objectId
Write-Host "  Tenant ID : $tenantId" -ForegroundColor Gray
Write-Host "  App ID    : $appId" -ForegroundColor Gray
Write-Host "  Object ID : $objectId" -ForegroundColor Gray

# ─── CONFIG (edit if you want a custom flow name) ───
$flowName = "{{FLOW_NAME}}"
$flowDescription = "{{FLOW_DESCRIPTION}}"

# ─── CONNECT ───
Write-Host "`n[2/6] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Write-Host "  Scopes: EventListener.ReadWrite.All, IdentityUserFlow.ReadWrite.All" -ForegroundColor Gray
try {
    $context = Get-MgContext
    $needsReconnect = $true
    if ($context -and $context.TenantId -eq $tenantId `
        -and $context.Scopes -contains "EventListener.ReadWrite.All" `
        -and $context.Scopes -contains "IdentityUserFlow.ReadWrite.All") {
        $needsReconnect = $false
    }
    if ($needsReconnect) {
        Connect-MgGraph -TenantId $tenantId `
            -Scopes "EventListener.ReadWrite.All","IdentityUserFlow.ReadWrite.All" `
            -NoWelcome -ErrorAction Stop
    }
    Write-Host "  Connected to tenant: $tenantId" -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ─── BUILD REQUEST BODY ───
Write-Host "`n[3/6] Building user flow request..." -ForegroundColor Cyan
$body = @{
    "@odata.type"     = "#microsoft.graph.externalUsersSelfServiceSignUpEventsFlow"
    displayName       = $flowName
    description       = $flowDescription
    priority          = 500
    onAuthenticationMethodLoadStart = @{
        "@odata.type"     = "#microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp"
        identityProviders = @(
            @{ id = "EmailPassword-OAUTH" }
        )
    }
    onInteractiveAuthFlowStart = @{
        "@odata.type"    = "#microsoft.graph.onInteractiveAuthFlowStartExternalUsersSelfServiceSignUp"
        isSignUpAllowed  = $true
    }
    onAttributeCollection = @{
        "@odata.type" = "#microsoft.graph.onAttributeCollectionExternalUsersSelfServiceSignUp"
        attributes = @(
{{ATTRIBUTES_BLOCK}}
        )
        attributeCollectionPage = @{
            views = @(
                @{
                    inputs = @(
{{ATTRIBUTE_INPUTS_BLOCK}}
                    )
                }
            )
        }
    }
} | ConvertTo-Json -Depth 20

Write-Host "  Request body:" -ForegroundColor Cyan
Write-Host $body -ForegroundColor Gray

# ─── CHECK IF FLOW ALREADY EXISTS ───
Write-Host "`n[4/6] Checking if flow '$flowName' already exists..." -ForegroundColor Cyan
$existingFlow = $null
try {
    $allFlows = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows"
    $existingFlow = $allFlows.value | Where-Object { $_.displayName -eq $flowName }
} catch {
    Write-Host "  Could not check existing flows (non-blocking). Will attempt create." -ForegroundColor Yellow
}

if ($existingFlow) {
    Write-Host "  Flow '$flowName' already exists (ID: $($existingFlow.id))." -ForegroundColor Yellow
    Write-Host "  Reusing existing flow." -ForegroundColor Green
    $flow = $existingFlow
} else {
    # ─── CREATE FLOW ───
    Write-Host "`n[5/6] Creating user flow via POST /v1.0/identity/authenticationEventsFlows..." -ForegroundColor Cyan
    try {
        $flow = Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows" `
            -Body $body `
            -ContentType "application/json"

        Write-Host "`n  SUCCESS - User flow created!" -ForegroundColor Green
        Write-Host "  ---------------------------------------" -ForegroundColor Green
        Write-Host "  Display Name : $($flow.displayName)" -ForegroundColor White
        Write-Host "  Flow ID      : $($flow.id)" -ForegroundColor White
        Write-Host "  App binding  : pending verification" -ForegroundColor White
        Write-Host "  ---------------------------------------" -ForegroundColor Green

    } catch {
        Write-Host "`n  FAILED - see error below" -ForegroundColor Red
        Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        if ($_.ErrorDetails.Message) {
            Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
        }
        Write-Host "`n  Common fixes:" -ForegroundColor Yellow
        Write-Host "  - Re-run Connect-MgGraph with EventListener.ReadWrite.All and IdentityUserFlow.ReadWrite.All" -ForegroundColor Yellow
        Write-Host "  - Caller needs role: External ID User Flow Administrator (or higher)" -ForegroundColor Yellow
        Write-Host "  - Flow displayName must be unique in the tenant (try changing `$flowName)" -ForegroundColor Yellow
        Write-Host "  - Confirm tenant is an External ID (CIAM) tenant, not workforce-only" -ForegroundColor Yellow
        exit 1
    }
}

# ─── ENSURE THE APP IS BOUND (works for both new and reused flows) ───
# App registrations can take several seconds to replicate into the user-flow
# service. Create/reuse the flow first, then converge its application binding.
Write-Host "`n[6/6] Ensuring the app is bound to the user flow..." -ForegroundColor Cyan
$flowUri = "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$($flow.id)"
$bound = $false
$lastBindingError = $null
function Test-IsBindingReplicationError {
    param($ErrorRecord)
    $status = $ErrorRecord.Exception.Response.StatusCode
    $message = if ($ErrorRecord.ErrorDetails.Message) {
        $ErrorRecord.ErrorDetails.Message
    } else {
        $ErrorRecord.Exception.Message
    }
    if ($message -match "not visible") { return $true }
    if ($message -match "already (exist|exists|included|added)" -and $message -notmatch "another|different") {
        return $true
    }
    if ($status -in @(429, 502, 503, 504)) { return $true }
    if ($message -match "timed out|timeout|temporarily unavailable|connection.*(?:closed|reset|failed)") {
        return $true
    }
    return $status -eq 404 -or (
        $status -eq 400 -and
        $message -match "replicat|is invalid|does not exist|not found|cannot find|not visible"
    )
}
for ($attempt = 1; $attempt -le 6 -and -not $bound; $attempt++) {
    try {
        $currentFlow = Invoke-MgGraphRequest -Method GET -Uri $flowUri
        $currentAppIds = @($currentFlow.conditions.applications.includeApplications | ForEach-Object { $_.appId })
        if ($currentAppIds -contains $appId) {
            $bound = $true
            break
        }

        $bindingBody = @{ appId = $appId } | ConvertTo-Json
        Invoke-MgGraphRequest -Method POST `
            -Uri "$flowUri/conditions/applications/includeApplications" `
            -Body $bindingBody -ContentType "application/json" | Out-Null

        Start-Sleep -Seconds 2
        $verifyFlow = Invoke-MgGraphRequest -Method GET -Uri $flowUri
        $verifiedAppIds = @($verifyFlow.conditions.applications.includeApplications | ForEach-Object { $_.appId })
        $bound = $verifiedAppIds -contains $appId
        if (-not $bound) { throw "The binding request returned, but the app is not visible on the flow yet." }
    } catch {
        $lastBindingError = $_
        try {
            $verifyAfterError = Invoke-MgGraphRequest -Method GET -Uri $flowUri
            $verifyAfterErrorIds = @($verifyAfterError.conditions.applications.includeApplications | ForEach-Object { $_.appId })
            if ($verifyAfterErrorIds -contains $appId) {
                $bound = $true
                break
            }
        } catch {
            # Preserve the original binding error for classification below.
        }
        if (-not (Test-IsBindingReplicationError $lastBindingError)) {
            Write-Host "  App binding failed permanently: $($lastBindingError.Exception.Message)" -ForegroundColor Red
            Write-Host "  Check permissions and whether this application is already associated with another user flow." -ForegroundColor Yellow
            exit 1
        }
        if ($attempt -lt 6) {
            Write-Host "  App binding is still replicating (attempt $attempt/6). Retrying..." -ForegroundColor Yellow
            Start-Sleep -Seconds (2 * $attempt)
        }
    }
}

if (-not $bound) {
    Write-Host "  FAILED to bind app $appId to flow $($flow.id)." -ForegroundColor Red
    if ($lastBindingError) { Write-Host "  $($lastBindingError.Exception.Message)" -ForegroundColor Red }
    Write-Host "  Wait 30 seconds and re-run this script. It will reuse the flow and retry only the missing binding." -ForegroundColor Yellow
    exit 1
}
Write-Host "  App binding verified." -ForegroundColor Green

# Reconcile any standard sign-up attributes that were added to the analyzed
# policy after this flow was first created.
try {
    $desiredFlow = $body | ConvertFrom-Json
    $desiredAttributes = @($desiredFlow.onAttributeCollection.attributes)
    $desiredInputs = @($desiredFlow.onAttributeCollection.attributeCollectionPage.views[0].inputs)
    $flowCastUri = "$flowUri/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow?`$expand=onAttributeCollection"
    $detailedFlow = Invoke-MgGraphRequest -Method GET -Uri $flowCastUri
    $currentAttributeIds = @($detailedFlow.onAttributeCollection.attributes | ForEach-Object { $_.id })
    $attributeRefUri = "$flowUri/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAttributeCollection/microsoft.graph.onAttributeCollectionExternalUsersSelfServiceSignUp/attributes/`$ref"

    foreach ($attribute in $desiredAttributes) {
        if ($currentAttributeIds -contains $attribute.id) { continue }
        $attributeRefBody = @{
            "@odata.id" = "https://graph.microsoft.com/v1.0/identity/userFlowAttributes/$($attribute.id)"
        } | ConvertTo-Json
        Invoke-MgGraphRequest -Method POST -Uri $attributeRefUri `
            -Body $attributeRefBody -ContentType "application/json" | Out-Null
        Write-Host "  Added missing sign-up attribute '$($attribute.displayName)'." -ForegroundColor Green
    }

    # Adding an attribute reference can leave default page settings (for example,
    # required=false). Reconcile the complete input list to match the generated plan.
    $attributesConverged = $false
    for ($attempt = 1; $attempt -le 5 -and -not $attributesConverged; $attempt++) {
        Start-Sleep -Seconds $attempt
        try {
            $detailedFlow = Invoke-MgGraphRequest -Method GET -Uri $flowCastUri
            $replicatedIds = @($detailedFlow.onAttributeCollection.attributes | ForEach-Object { $_.id })
            $attributesConverged = @(
                $desiredAttributes | Where-Object { $replicatedIds -notcontains $_.id }
            ).Count -eq 0
        } catch {
            if ($attempt -eq 5) { throw }
        }
    }
    if (-not $attributesConverged) {
        throw "Sign-up attribute references did not converge after retrying."
    }
    $currentInputs = @($detailedFlow.onAttributeCollection.attributeCollectionPage.views[0].inputs)
    $currentViews = @($detailedFlow.onAttributeCollection.attributeCollectionPage.views)
    $desiredByAttribute = @{}
    foreach ($desiredInput in $desiredInputs) {
        $desiredByAttribute[[string]$desiredInput.attribute] = $desiredInput
    }

    $mergedInputs = @()
    foreach ($currentInput in $currentInputs) {
        $attributeId = [string]$currentInput.attribute
        $desiredInput = $desiredByAttribute[$attributeId]
        $inputCopy = $currentInput | ConvertTo-Json -Depth 20 | ConvertFrom-Json -AsHashtable
        if ($desiredInput) {
            $inputCopy["attribute"] = $attributeId
            $inputCopy["label"] = [string]$desiredInput.label
            $inputCopy["inputType"] = [string]$desiredInput.inputType
            $inputCopy["hidden"] = [bool]$desiredInput.hidden
            $inputCopy["editable"] = [bool]$desiredInput.editable
            $inputCopy["writeToDirectory"] = [bool]$desiredInput.writeToDirectory
            $inputCopy["required"] = [bool]$desiredInput.required
            $mergedInputs += $inputCopy
            $desiredByAttribute.Remove($attributeId)
        } else {
            $mergedInputs += $inputCopy
        }
    }
    foreach ($entry in $desiredByAttribute.GetEnumerator()) {
        $desiredInput = $entry.Value
        $mergedInputs += @{
            attribute        = [string]$desiredInput.attribute
            label            = [string]$desiredInput.label
            inputType        = [string]$desiredInput.inputType
            hidden           = [bool]$desiredInput.hidden
            editable         = [bool]$desiredInput.editable
            writeToDirectory = [bool]$desiredInput.writeToDirectory
            required         = [bool]$desiredInput.required
        }
    }

    $settingsMatch = $true
    foreach ($desiredInput in $desiredInputs) {
        $currentInput = $currentInputs | Where-Object { $_.attribute -eq $desiredInput.attribute } | Select-Object -First 1
        if (-not $currentInput `
            -or $currentInput.label -ne $desiredInput.label `
            -or $currentInput.inputType -ne $desiredInput.inputType `
            -or [bool]$currentInput.hidden -ne [bool]$desiredInput.hidden `
            -or [bool]$currentInput.editable -ne [bool]$desiredInput.editable `
            -or [bool]$currentInput.writeToDirectory -ne [bool]$desiredInput.writeToDirectory `
            -or [bool]$currentInput.required -ne [bool]$desiredInput.required) {
            $settingsMatch = $false
            break
        }
    }

    if (-not $settingsMatch) {
        $mergedViews = @()
        if ($currentViews.Count -gt 0) {
            for ($viewIndex = 0; $viewIndex -lt $currentViews.Count; $viewIndex++) {
                $viewCopy = $currentViews[$viewIndex] | ConvertTo-Json -Depth 20 | ConvertFrom-Json -AsHashtable
                if ($viewIndex -eq 0) { $viewCopy["inputs"] = $mergedInputs }
                $mergedViews += $viewCopy
            }
        } else {
            $mergedViews = @(@{ inputs = $mergedInputs })
        }
        $pagePatch = @{
            "@odata.type" = "#microsoft.graph.externalUsersSelfServiceSignUpEventsFlow"
            onAttributeCollection = @{
                "@odata.type" = "#microsoft.graph.onAttributeCollectionExternalUsersSelfServiceSignUp"
                attributeCollectionPage = @{
                    views = $mergedViews
                }
            }
        } | ConvertTo-Json -Depth 10
        Invoke-MgGraphRequest -Method PATCH -Uri $flowUri `
            -Body $pagePatch -ContentType "application/json" | Out-Null

        $pageSettingsConverged = $false
        for ($attempt = 1; $attempt -le 5 -and -not $pageSettingsConverged; $attempt++) {
            Start-Sleep -Seconds $attempt
            try {
                $verifiedFlow = Invoke-MgGraphRequest -Method GET -Uri $flowCastUri
                $verifiedInputs = @($verifiedFlow.onAttributeCollection.attributeCollectionPage.views[0].inputs)
                $pageSettingsConverged = $true
                foreach ($desiredInput in $desiredInputs) {
                    $verifiedInput = $verifiedInputs | Where-Object { $_.attribute -eq $desiredInput.attribute } | Select-Object -First 1
                    if (-not $verifiedInput `
                        -or $verifiedInput.label -ne $desiredInput.label `
                        -or $verifiedInput.inputType -ne $desiredInput.inputType `
                        -or [bool]$verifiedInput.hidden -ne [bool]$desiredInput.hidden `
                        -or [bool]$verifiedInput.editable -ne [bool]$desiredInput.editable `
                        -or [bool]$verifiedInput.writeToDirectory -ne [bool]$desiredInput.writeToDirectory `
                        -or [bool]$verifiedInput.required -ne [bool]$desiredInput.required) {
                        $pageSettingsConverged = $false
                        break
                    }
                }
            } catch {
                if ($attempt -eq 5) { throw }
            }
        }
        if (-not $pageSettingsConverged) {
            throw "Sign-up page settings did not converge after retrying."
        }
        Write-Host "  Sign-up page labels and required/write settings reconciled." -ForegroundColor Green
    }
} catch {
    Write-Host "  FAILED to reconcile sign-up attributes: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  The flow exists, but it may not collect every attribute from the source policy." -ForegroundColor Yellow
    exit 1
}

$createdFlowContext = @{
    flowId      = $flow.id
    flowName    = $flow.displayName
    appId       = $appId
    tenantId    = $tenantId
    createdAt   = (Get-Date).ToString("o")
}
$createdFlowContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-created-flow.json"
Write-Host "  Saved flow context to .last-created-flow.json" -ForegroundColor Cyan

Write-Host "`nNEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Open Entra admin center -> External Identities -> User flows" -ForegroundColor White
Write-Host "     https://entra.microsoft.com/#view/Microsoft_AAD_IAM/UserFlowsBladeV2" -ForegroundColor Gray
Write-Host "  2. Verify '$flowName' is listed." -ForegroundColor White
Write-Host "  3. {{NEXT_STEP}}" -ForegroundColor White
