# ═══════════════════════════════════════════════════════════════════
#  03 — Smoke Test: Native Auth /initiate
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Prove the app + service principal + user flow are wired
#           correctly for native auth by calling /oauth2/v2.0/initiate
#           with a non-existent user.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  Expected: HTTP 400 with `error: "user_not_found"` (or similar
#            enumeration-safe error). This means the request was
#            understood, the app is authorized, and the flow is alive.
#
#  Failures to look for:
#    - unauthorized_client      → app not bound to flow / SP missing
#    - unsupported_challenge_type → flow has no EmailPassword IdP
#    - invalid_request          → URL or body shape wrong
#    - 404 / connection error   → wrong subdomain / tenant
#
#  Chains from: .last-created-app.json + .last-created-flow.json
#  Run:         pwsh ./03-smoke-test-native-auth.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT ───
Write-Host "`n[1/4] Reading context from scripts 01 + 02..." -ForegroundColor Cyan
$appCtx  = "$PSScriptRoot\.last-created-app.json"
$flowCtx = "$PSScriptRoot\.last-created-flow.json"
if (-not (Test-Path $appCtx) -or -not (Test-Path $flowCtx)) {
    Write-Host "  Missing context files. Run scripts 01 and 02 first." -ForegroundColor Red
    exit 1
}
$appContext  = Get-Content $appCtx  -Raw | ConvertFrom-Json
$flowContext = Get-Content $flowCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$appId    = $appContext.appId
$flowId   = $flowContext.flowId
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  App    : $appId" -ForegroundColor Gray
Write-Host "  Flow   : $flowId ($($flowContext.flowName))" -ForegroundColor Gray

# ─── DISCOVER TENANT SUBDOMAIN ───
Write-Host "`n[2/4] Discovering tenant subdomain..." -ForegroundColor Cyan
try {
    $context = Get-MgContext
    if (-not $context -or $context.TenantId -ne $tenantId -or $context.Scopes -notcontains "Organization.Read.All") {
        Connect-MgGraph -TenantId $tenantId -Scopes "Organization.Read.All" -NoWelcome -ErrorAction Stop
    }
    $org = Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/v1.0/organization"
    $initialDomain = ($org.value[0].verifiedDomains | Where-Object { $_.isInitial }).name
    if (-not $initialDomain) { throw "The tenant has no initial verified domain." }
    $subdomain = $initialDomain.Split('.')[0]
    Write-Host "  Initial domain : $initialDomain" -ForegroundColor Gray
    Write-Host "  Subdomain      : $subdomain" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED to discover the tenant subdomain: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  Confirm the tenant ID and grant Organization.Read.All, then re-run." -ForegroundColor Yellow
    exit 1
}

# ─── BUILD REQUEST ───
$nativeAuthHost = "$subdomain.ciamlogin.com"
$nativeAuthUrl  = "https://$nativeAuthHost/$initialDomain/oauth2/v2.0/initiate"
$testEmail      = "smoketest-nobody-$(Get-Random)@example.invalid"

Write-Host "`n[3/4] Calling POST $nativeAuthUrl ..." -ForegroundColor Cyan
Write-Host "  Body fields:" -ForegroundColor Gray
Write-Host "    client_id      = $appId" -ForegroundColor Gray
Write-Host "    username       = $testEmail" -ForegroundColor Gray
Write-Host "    challenge_type = password redirect" -ForegroundColor Gray

$body = @{
    client_id      = $appId
    username       = $testEmail
    challenge_type = "password redirect"
}

# ─── INVOKE ───
$status = 0
try {
    $response = Invoke-RestMethod `
        -Uri $nativeAuthUrl `
        -Method POST `
        -ContentType "application/x-www-form-urlencoded" `
        -Body $body `
        -SkipHttpErrorCheck `
        -StatusCodeVariable status
} catch {
    Write-Host "`n  Network error: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "  Likely a wrong subdomain. Try the request manually with:" -ForegroundColor Yellow
    Write-Host "  Invoke-WebRequest https://$nativeAuthHost/$tenantId/v2.0/.well-known/openid-configuration" -ForegroundColor Yellow
    exit 1
}

# ─── INTERPRET ───
Write-Host "`n[4/4] Response:" -ForegroundColor Cyan
Write-Host "  HTTP $status" -ForegroundColor Gray
Write-Host "  Body:" -ForegroundColor Gray
$response | ConvertTo-Json -Depth 5 | ForEach-Object { Write-Host "    $_" -ForegroundColor Gray }

Write-Host "`n  Verdict:" -ForegroundColor Cyan
$errCode = $response.error
$errSub  = $response.suberror

if ($status -eq 200 -and $response.continuation_token) {
    Write-Host "  PASS - Got continuation_token. Native auth is fully wired." -ForegroundColor Green
    exit 0
}
elseif ($errCode -in @("user_not_found", "invalid_grant") -or $errSub -eq "user_not_found") {
    Write-Host "  PASS - Got expected '$errCode' for non-existent test user." -ForegroundColor Green
    Write-Host "     App is authorized, flow accepts requests, EmailPassword IdP is active." -ForegroundColor Green
    exit 0
}
elseif ($errCode -eq "unauthorized_client") {
    Write-Host "  FAIL - 'unauthorized_client'" -ForegroundColor Red
    Write-Host "     Means: app reg not bound to the flow, or service principal missing." -ForegroundColor Red
    Write-Host "     Check: re-run 01, confirm flow.conditions.applications includes appId." -ForegroundColor Yellow
    exit 1
}
elseif ($errCode -eq "unsupported_challenge_type") {
    Write-Host "  FAIL - 'unsupported_challenge_type'" -ForegroundColor Red
    Write-Host "     Means: flow has no EmailPassword IdP, or native auth not enabled on app." -ForegroundColor Red
    Write-Host "     Check: flow.onAuthenticationMethodLoadStart.identityProviders should contain EmailPassword-OAUTH." -ForegroundColor Yellow
    Write-Host "     Check: app.nativeAuthenticationApisEnabled should be 'all'." -ForegroundColor Yellow
    exit 1
}
elseif ($errCode -eq "invalid_client") {
    Write-Host "  FAIL - 'invalid_client' (suberror='$errSub')" -ForegroundColor Red
    Write-Host "     Check the client ID and app.nativeAuthenticationApisEnabled." -ForegroundColor Yellow
    if ($errSub -eq "nativeauthapi_disabled") {
        Write-Host "     Native auth is disabled on the app registration. Re-run script 01." -ForegroundColor Yellow
    }
    exit 1
}
elseif ($errCode -eq "invalid_request") {
    Write-Host "  FAIL - 'invalid_request'" -ForegroundColor Red
    Write-Host "     Full error_description: $($response.error_description)" -ForegroundColor Yellow
    exit 1
}
else {
    Write-Host "  FAIL - unexpected response: error='$errCode' suberror='$errSub'" -ForegroundColor Red
    Write-Host "     Read the body above. Compare against External ID native auth docs." -ForegroundColor Yellow
    exit 1
}
