# ═══════════════════════════════════════════════════════════════════
#  04 — Add Google as a Social Identity Provider (and bind to flow)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Provision Google as a social IdP in the External ID tenant
#           and attach it to the email+password user flow created by
#           script 02. After this, the user flow accepts Google sign-in
#           in addition to email+password.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  PREREQUISITE — Google Cloud Console setup (one-time, manual):
#    1. https://console.cloud.google.com → create project
#    2. APIs & services → OAuth consent screen → User Type "External" → create
#    3. Authorized domains: add `ciamlogin.com` and `microsoftonline.com`
#    4. Credentials → Create credentials → OAuth client ID → "Web application"
#    5. Add all 7 redirect URIs listed below in the CONFIG block (this
#       script PRINTS them with your tenant values substituted in)
#    6. Record the Client ID and Client Secret → paste into CONFIG below
#
#  Chains from: .last-created-app.json + .last-created-flow.json
#  Produces:    .last-added-google-idp.json (idp id, display name)
#
#  Run: pwsh ./04-add-google-idp.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPTS 01 + 02 ───
Write-Host "`n[1/7] Reading context from scripts 01 + 02..." -ForegroundColor Cyan
$appCtx  = "$PSScriptRoot\.last-created-app.json"
$flowCtx = "$PSScriptRoot\.last-created-flow.json"
if (-not (Test-Path $appCtx) -or -not (Test-Path $flowCtx)) {
    Write-Host "  Missing context files. Run scripts 01 and 02 first." -ForegroundColor Red
    exit 1
}
$appContext  = Get-Content $appCtx  -Raw | ConvertFrom-Json
$flowContext = Get-Content $flowCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$appId    = $appContext.appId
$flowId   = $flowContext.flowId
$flowName = $flowContext.flowName
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  App    : $appId" -ForegroundColor Gray
Write-Host "  Flow   : $flowId ($flowName)" -ForegroundColor Gray

# ─── CONFIG (edit before running) ───
$googleClientId     = "{{GOOGLE_CLIENT_ID}}"
$googleClientSecret = "{{GOOGLE_CLIENT_SECRET}}"
$idpDisplayName     = "{{GOOGLE_IDP_DISPLAY_NAME}}"

# ─── CONNECT ───
Write-Host "`n[2/7] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Write-Host "  Scopes: IdentityProvider.ReadWrite.All, EventListener.ReadWrite.All, Organization.Read.All" -ForegroundColor Gray
try {
    $context = Get-MgContext
    $needsReconnect = $true
    if ($context -and $context.TenantId -eq $tenantId `
        -and $context.Scopes -contains "IdentityProvider.ReadWrite.All" `
        -and $context.Scopes -contains "EventListener.ReadWrite.All" `
        -and $context.Scopes -contains "Organization.Read.All") {
        $needsReconnect = $false
    }
    if ($needsReconnect) {
        Connect-MgGraph -TenantId $tenantId `
            -Scopes "IdentityProvider.ReadWrite.All","EventListener.ReadWrite.All","Organization.Read.All" `
            -NoWelcome -ErrorAction Stop
    }
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ─── DISCOVER TENANT SUBDOMAIN (for the redirect URIs Google needs) ───
Write-Host "`n[3/7] Discovering tenant subdomain..." -ForegroundColor Cyan
try {
    $org = Invoke-MgGraphRequest -Method GET -Uri "https://graph.microsoft.com/v1.0/organization"
    $initialDomain  = ($org.value[0].verifiedDomains | Where-Object { $_.isInitial }).name
    $tenantSubdomain = $initialDomain.Split('.')[0]
    Write-Host "  Initial domain : $initialDomain" -ForegroundColor Gray
    Write-Host "  Subdomain      : $tenantSubdomain" -ForegroundColor Gray
} catch {
    Write-Host "  Couldn't auto-discover the tenant subdomain. Using a placeholder." -ForegroundColor Yellow
    Write-Host "  (Edit `$tenantSubdomain in this script if that's wrong.)" -ForegroundColor Yellow
    Write-Host "  Reason: $($_.Exception.Message)" -ForegroundColor DarkGray
    $tenantSubdomain = "yourtenant"
}

# ─── PRINT REQUIRED GOOGLE REDIRECT URIs ───
Write-Host "`nREDIRECT URIS YOUR GOOGLE OAUTH CLIENT MUST HAVE:" -ForegroundColor Yellow
Write-Host "  (copy these into Google Cloud Console -> Credentials -> your OAuth client -> Valid OAuth redirect URIs)" -ForegroundColor Gray
$redirectUris = @(
    "https://login.microsoftonline.com",
    "https://login.microsoftonline.com/te/$tenantId/oauth2/authresp",
    "https://login.microsoftonline.com/te/$tenantSubdomain.onmicrosoft.com/oauth2/authresp",
    "https://$tenantId.ciamlogin.com/$tenantId/federation/oidc/accounts.google.com",
    "https://$tenantId.ciamlogin.com/$tenantSubdomain.onmicrosoft.com/federation/oidc/accounts.google.com",
    "https://$tenantSubdomain.ciamlogin.com/$tenantId/federation/oauth2",
    "https://$tenantSubdomain.ciamlogin.com/$tenantSubdomain.onmicrosoft.com/federation/oauth2"
)
foreach ($uri in $redirectUris) {
    Write-Host "    $uri" -ForegroundColor White
}

# ─── GUARD: credentials filled in? ───
if ($googleClientId -like "*EDIT_ME*" -or $googleClientSecret -like "*EDIT_ME*") {
    Write-Host "`n  CONFIG REQUIRED - client credentials are not filled in." -ForegroundColor Yellow
    Write-Host "  Set up Google OAuth client (see PREREQUISITE in header)," -ForegroundColor Yellow
    Write-Host "  paste Client ID and Client Secret into the CONFIG block, then re-run." -ForegroundColor Yellow
    exit 2
}

# ─── CHECK IF GOOGLE IDP ALREADY EXISTS (idempotent) ───
Write-Host "`n[4/7] Checking for existing Google IdP..." -ForegroundColor Cyan
try {
    $existing = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders"

    $googleIdp = $existing.value | Where-Object { $_.identityProviderType -eq "Google" } | Select-Object -First 1

    if ($googleIdp) {
        Write-Host "  Google IdP already exists - refreshing the supplied credentials." -ForegroundColor Yellow
        $updateBody = @{
            displayName  = $idpDisplayName
            clientId     = $googleClientId
            clientSecret = $googleClientSecret
        } | ConvertTo-Json -Depth 10
        Invoke-MgGraphRequest `
            -Method PATCH `
            -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders/$($googleIdp.id)" `
            -Body $updateBody `
            -ContentType "application/json" | Out-Null
        Write-Host "    id          : $($googleIdp.id)" -ForegroundColor Gray
        Write-Host "    displayName : $idpDisplayName" -ForegroundColor Gray
    } else {
        # ─── CREATE GOOGLE IDP ───
        Write-Host "`n[5/7] Creating Google IdP via POST /v1.0/identity/identityProviders..." -ForegroundColor Cyan
        $idpBody = @{
            "@odata.type"        = "microsoft.graph.socialIdentityProvider"
            displayName          = $idpDisplayName
            identityProviderType = "Google"
            clientId             = $googleClientId
            clientSecret         = $googleClientSecret
        } | ConvertTo-Json -Depth 10

        $googleIdp = Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders" `
            -Body $idpBody `
            -ContentType "application/json"

        Write-Host "  Created." -ForegroundColor Green
        Write-Host "    id          : $($googleIdp.id)" -ForegroundColor White
        Write-Host "    displayName : $($googleIdp.displayName)" -ForegroundColor White
    }
} catch {
    Write-Host "`n  FAILED to create/read Google IdP" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host "`n  Common fixes:" -ForegroundColor Yellow
    Write-Host "  - Need role: External Identity Provider Administrator" -ForegroundColor Yellow
    Write-Host "  - Confirm scope IdentityProvider.ReadWrite.All granted on Connect-MgGraph" -ForegroundColor Yellow
    Write-Host "  - Client secret must be the actual secret value from Google, not the secret id" -ForegroundColor Yellow
    exit 1
}

# ─── READ CURRENT USER FLOW (to merge identityProviders array) ───
Write-Host "`n[6/7] Reading current user flow state..." -ForegroundColor Cyan
try {
    $flow = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId"

    $existingIdps = @($flow.onAuthenticationMethodLoadStart.identityProviders)
    $existingIds  = @($existingIdps | ForEach-Object { $_.id })
    Write-Host "  Current IdPs on flow: $($existingIds -join ', ')" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED to read flow $flowId" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    exit 1
}

# ─── ADD GOOGLE TO THE FLOW THROUGH THE DEDICATED GA ENDPOINT ───
if ($existingIds -contains $googleIdp.id) {
    Write-Host "  Google IdP already on flow - no add needed." -ForegroundColor Yellow
} else {
    Write-Host "`n[7/7] Adding Google IdP to the flow..." -ForegroundColor Cyan
    $refBody = @{
        "@odata.id" = "https://graph.microsoft.com/v1.0/identity/identityProviders/$($googleIdp.id)"
    } | ConvertTo-Json

    try {
        Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/`$ref" `
            -Body $refBody `
            -ContentType "application/json" | Out-Null

        Write-Host "`n  Add succeeded." -ForegroundColor Green
    } catch {
        Write-Host "`n  ADD TO FLOW FAILED" -ForegroundColor Red
        Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        if ($_.ErrorDetails.Message) {
            Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
        }
        Write-Host "`n  Confirm EventListener.ReadWrite.All is granted and the user flow exists." -ForegroundColor Yellow
        exit 1
    }
}

# ─── VERIFY ───
Write-Host "`n  Re-reading flow to verify..." -ForegroundColor Cyan
$finalIds = @()
for ($attempt = 1; $attempt -le 5; $attempt++) {
    $verifyFlow = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId"
    $finalIds = @($verifyFlow.onAuthenticationMethodLoadStart.identityProviders | ForEach-Object { $_.id })
    if ($finalIds -contains $googleIdp.id) { break }
    Start-Sleep -Seconds (2 * $attempt)
}
if ($finalIds -notcontains $googleIdp.id) {
    Write-Host "  FAILED - Graph did not show Google on the flow after the add operation." -ForegroundColor Red
    exit 1
}
Write-Host "  Flow now has IdPs: $($finalIds -join ', ')" -ForegroundColor White

# ─── SAVE CONTEXT ───
$googleIdpContext = @{
    idpId       = $googleIdp.id
    displayName = $idpDisplayName
    flowId      = $flowId
    tenantId    = $tenantId
    addedAt     = (Get-Date).ToString("o")
}
$googleIdpContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-added-google-idp.json"
Write-Host "`n  Saved IdP context to .last-added-google-idp.json" -ForegroundColor Cyan

Write-Host "`n  SUCCESS" -ForegroundColor Green
Write-Host "  ---------------------------------------" -ForegroundColor Green
Write-Host "  Google IdP id     : $($googleIdp.id)" -ForegroundColor White
Write-Host "  Display name      : $($googleIdp.displayName)" -ForegroundColor White
Write-Host "  Bound to flow     : $flowName ($flowId)" -ForegroundColor White
Write-Host "  Flow IdP roster   : $($finalIds -join ', ')" -ForegroundColor White
Write-Host "  ---------------------------------------" -ForegroundColor Green

Write-Host "`nNEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Entra admin center -> External Identities -> All identity providers" -ForegroundColor White
Write-Host "     Confirm '$idpDisplayName' (Google) is listed." -ForegroundColor Gray
Write-Host "  2. External Identities -> User flows -> $flowName -> Identity providers" -ForegroundColor White
Write-Host "     Confirm Google is checked. NOTE: the admin center caches this page." -ForegroundColor Gray
Write-Host "     If Google looks unchecked, hard-refresh (Ctrl+Shift+R) and re-open the flow." -ForegroundColor Gray
Write-Host "     The 'Flow IdP roster' printed above (read live from Graph) is the source of truth." -ForegroundColor Gray
Write-Host "  3. REAL TEST (definitive) - open this sign-in page and look for a 'Sign in with Google' button:" -ForegroundColor White
Write-Host "     https://$tenantSubdomain.ciamlogin.com/$tenantId/oauth2/v2.0/authorize?client_id=$appId&response_type=code&redirect_uri=msauth://com.test.toolapp/callback&scope=openid&prompt=login" -ForegroundColor Gray
Write-Host "     If the button is missing, wait 1-2 minutes for the flow to propagate, then retry." -ForegroundColor Gray
Write-Host "     If clicking it errors, your Google OAuth client is missing one of the 7 redirect URIs printed above." -ForegroundColor Gray
