# ═══════════════════════════════════════════════════════════════════
#  05 — Add Facebook as a Social Identity Provider (and bind to flow)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Provision Facebook as a social IdP in the External ID tenant
#           and attach it to the user flow created by script 02. After
#           this, the user flow accepts Facebook sign-in in addition to
#           any existing identity providers.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  PREREQUISITE — Facebook Developer Console setup (one-time, manual):
#    1. https://developers.facebook.com → create app (type: "Consumer")
#    2. Add "Facebook Login" product
#    3. Settings → Basic → record App ID and App Secret
#    4. Facebook Login → Settings → Valid OAuth Redirect URIs:
#       Add: https://login.microsoftonline.com/common/oauth2/nativeclient
#       Add: https://<tenant-subdomain>.ciamlogin.com
#    5. Paste App ID and App Secret into CONFIG below
#
#  Chains from: .last-created-app.json + .last-created-flow.json
#  Produces:    .last-added-facebook-idp.json (idp id, display name)
#
#  Run: pwsh ./05-add-facebook-idp.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPTS 01 + 02 ───
Write-Host "`n[1/6] Reading context from scripts 01 + 02..." -ForegroundColor Cyan
$appCtx  = "$PSScriptRoot\.last-created-app.json"
$flowCtx = "$PSScriptRoot\.last-created-flow.json"
if (-not (Test-Path $appCtx) -or -not (Test-Path $flowCtx)) {
    Write-Host "  Missing context files. Run scripts 01 and 02 first." -ForegroundColor Red
    exit 1
}
$appContext  = Get-Content $appCtx  -Raw | ConvertFrom-Json
$flowContext = Get-Content $flowCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$appId    = $appContext.appId
$flowId   = $flowContext.flowId
$flowName = $flowContext.flowName
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  App    : $appId" -ForegroundColor Gray
Write-Host "  Flow   : $flowId ($flowName)" -ForegroundColor Gray

# ─── CONFIG (edit before running) ───
$facebookAppId      = "{{FACEBOOK_APP_ID}}"
$facebookAppSecret  = "{{FACEBOOK_APP_SECRET}}"
$idpDisplayName     = "{{FACEBOOK_IDP_DISPLAY_NAME}}"

# ─── CONNECT ───
Write-Host "`n[2/6] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Write-Host "  Scopes: IdentityProvider.ReadWrite.All, EventListener.ReadWrite.All" -ForegroundColor Gray
try {
    $context = Get-MgContext
    $needsReconnect = $true
    if ($context -and $context.TenantId -eq $tenantId `
        -and $context.Scopes -contains "IdentityProvider.ReadWrite.All" `
        -and $context.Scopes -contains "EventListener.ReadWrite.All") {
        $needsReconnect = $false
    }
    if ($needsReconnect) {
        Connect-MgGraph -TenantId $tenantId `
            -Scopes "IdentityProvider.ReadWrite.All","EventListener.ReadWrite.All" `
            -NoWelcome -ErrorAction Stop
    }
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ─── GUARD: credentials filled in? ───
if ($facebookAppId -like "*EDIT_ME*" -or $facebookAppSecret -like "*EDIT_ME*") {
    Write-Host "`n  CONFIG REQUIRED - client credentials are not filled in." -ForegroundColor Yellow
    Write-Host "  Set up a Facebook app (see PREREQUISITE in header)," -ForegroundColor Yellow
    Write-Host "  paste App ID and App Secret into the CONFIG block, then re-run." -ForegroundColor Yellow
    exit 2
}

# ─── CHECK IF FACEBOOK IDP ALREADY EXISTS (idempotent) ───
Write-Host "`n[3/6] Checking for existing Facebook IdP..." -ForegroundColor Cyan
try {
    $existing = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders"

    $facebookIdp = $existing.value | Where-Object { $_.identityProviderType -eq "Facebook" } | Select-Object -First 1

    if ($facebookIdp) {
        Write-Host "  Facebook IdP already exists - refreshing the supplied credentials." -ForegroundColor Yellow
        $updateBody = @{
            displayName  = $idpDisplayName
            clientId     = $facebookAppId
            clientSecret = $facebookAppSecret
        } | ConvertTo-Json -Depth 10
        Invoke-MgGraphRequest `
            -Method PATCH `
            -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders/$($facebookIdp.id)" `
            -Body $updateBody `
            -ContentType "application/json" | Out-Null
        Write-Host "    id          : $($facebookIdp.id)" -ForegroundColor Gray
        Write-Host "    displayName : $idpDisplayName" -ForegroundColor Gray
    } else {
        # ─── CREATE FACEBOOK IDP ───
        Write-Host "`n[4/6] Creating Facebook IdP via POST /v1.0/identity/identityProviders..." -ForegroundColor Cyan
        $idpBody = @{
            "@odata.type"        = "#microsoft.graph.socialIdentityProvider"
            displayName          = $idpDisplayName
            identityProviderType = "Facebook"
            clientId             = $facebookAppId
            clientSecret         = $facebookAppSecret
        } | ConvertTo-Json -Depth 10

        $facebookIdp = Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/identityProviders" `
            -Body $idpBody `
            -ContentType "application/json"

        Write-Host "  Created." -ForegroundColor Green
        Write-Host "    id          : $($facebookIdp.id)" -ForegroundColor White
        Write-Host "    displayName : $($facebookIdp.displayName)" -ForegroundColor White
    }
} catch {
    Write-Host "`n  FAILED to create/read Facebook IdP" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    Write-Host "`n  Common fixes:" -ForegroundColor Yellow
    Write-Host "  - Need role: External Identity Provider Administrator" -ForegroundColor Yellow
    Write-Host "  - Confirm scope IdentityProvider.ReadWrite.All granted on Connect-MgGraph" -ForegroundColor Yellow
    Write-Host "  - App Secret must be the actual secret value from Facebook, not the secret id" -ForegroundColor Yellow
    exit 1
}

# ─── READ CURRENT USER FLOW (to merge identityProviders array) ───
Write-Host "`n[5/6] Reading current user flow state..." -ForegroundColor Cyan
try {
    $flow = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId"

    $existingIdps = @($flow.onAuthenticationMethodLoadStart.identityProviders)
    $existingIds  = @($existingIdps | ForEach-Object { $_.id })
    Write-Host "  Current IdPs on flow: $($existingIds -join ', ')" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED to read flow $flowId" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) {
        Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
    }
    exit 1
}

# ─── PATCH FLOW: add Facebook IdP to identityProviders ───
if ($existingIds -contains $facebookIdp.id) {
    Write-Host "  Facebook IdP already on flow - no PATCH needed." -ForegroundColor Yellow
} else {
    Write-Host "`n[6/6] PATCHing flow to add Facebook IdP..." -ForegroundColor Cyan

    $refBody = @{
        "@odata.id" = "https://graph.microsoft.com/v1.0/identity/identityProviders/$($facebookIdp.id)"
    } | ConvertTo-Json

    try {
        Invoke-MgGraphRequest `
            -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAuthenticationMethodLoadStart/microsoft.graph.onAuthenticationMethodLoadStartExternalUsersSelfServiceSignUp/identityProviders/`$ref" `
            -Body $refBody `
            -ContentType "application/json" | Out-Null

        Write-Host "`n  PATCH succeeded." -ForegroundColor Green
    } catch {
        Write-Host "`n  PATCH FAILED" -ForegroundColor Red
        Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        if ($_.ErrorDetails.Message) {
            Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red
        }
        Write-Host "`n  Try checking:" -ForegroundColor Yellow
        Write-Host "  - The PATCH shape (needs @odata.bind ref)" -ForegroundColor Yellow
        Write-Host "  - That EventListener.ReadWrite.All scope is granted" -ForegroundColor Yellow
        exit 1
    }
}

# ─── VERIFY ───
Write-Host "`n  Re-reading flow to verify..." -ForegroundColor Cyan
$finalIds = @()
for ($attempt = 1; $attempt -le 5; $attempt++) {
    $verifyFlow = Invoke-MgGraphRequest `
        -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId"
    $finalIds = @($verifyFlow.onAuthenticationMethodLoadStart.identityProviders | ForEach-Object { $_.id })
    if ($finalIds -contains $facebookIdp.id) { break }
    Start-Sleep -Seconds (2 * $attempt)
}
if ($finalIds -notcontains $facebookIdp.id) {
    Write-Host "  FAILED - Graph did not show Facebook on the flow after the add operation." -ForegroundColor Red
    exit 1
}
Write-Host "  Flow now has IdPs: $($finalIds -join ', ')" -ForegroundColor White

# ─── SAVE CONTEXT ───
$facebookIdpContext = @{
    idpId       = $facebookIdp.id
    displayName = $idpDisplayName
    flowId      = $flowId
    flowName    = $flowName
}
$facebookIdpContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-added-facebook-idp.json"
Write-Host "`n  Saved Facebook IdP context to .last-added-facebook-idp.json" -ForegroundColor Cyan

Write-Host "`nSUCCESS - Facebook IdP provisioned and bound to flow '$flowName'." -ForegroundColor Green
Write-Host "   Users can now sign in with Facebook in addition to existing providers.`n" -ForegroundColor Green
Write-Host "   The 'Flow now has IdPs' roster above (read live from Graph) is the source of truth." -ForegroundColor Gray
Write-Host "   If the admin center shows Facebook unchecked, hard-refresh (Ctrl+Shift+R) - it caches.`n" -ForegroundColor Gray
