# ═══════════════════════════════════════════════════════════════════
#  07 — Enable Email One-Time Passcode (OTP) Authentication
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Enable email OTP as an authentication method in the
#           External ID tenant. This allows users to sign in or
#           verify their email using a one-time passcode.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  What this does:
#    - Enables the Email authentication method at the tenant level
#    - Allows External ID users to use email OTP for verification
#
#  Chains from: .last-created-app.json (for tenant context)
#
#  Run: pwsh ./07-enable-email-otp.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/4] Reading context from script 01..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing context file. Run script 01 first." -ForegroundColor Red
    exit 1
}
$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray

# ─── CONNECT ───
Write-Host "`n[2/4] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "Policy.ReadWrite.AuthenticationMethod" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── CHECK CURRENT STATUS ───
Write-Host "`n[3/4] Checking current email OTP configuration..." -ForegroundColor Cyan
try {
    $currentConfig = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email"
    $currentState = $currentConfig.state
    Write-Host "  Current state: $currentState" -ForegroundColor Gray
    Write-Host "  External ID use: $($currentConfig.allowExternalIdToUseEmailOtp)" -ForegroundColor Gray

    if ($currentState -eq "enabled" -and $currentConfig.allowExternalIdToUseEmailOtp -eq "enabled") {
        Write-Host "  Email OTP is already enabled. No changes needed." -ForegroundColor Green
        Write-Host "`n  Done!" -ForegroundColor Cyan
        exit 0
    }
} catch {
    Write-Host "  Could not read current config (may not exist yet). Proceeding..." -ForegroundColor Yellow
}

# ─── ENABLE EMAIL OTP ───
Write-Host "`n[4/4] Enabling email OTP authentication method..." -ForegroundColor Cyan
$body = @{
    "@odata.type" = "#microsoft.graph.emailAuthenticationMethodConfiguration"
    state = "enabled"
    allowExternalIdToUseEmailOtp = "enabled"
} | ConvertTo-Json -Depth 5

try {
    Invoke-MgGraphRequest -Method PATCH `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email" `
        -Body $body `
        -ContentType "application/json"

    Write-Host "  Email OTP enabled successfully!" -ForegroundColor Green
} catch {
    $err = $_
    Write-Host "  FAILED - see error below" -ForegroundColor Red
    Write-Host "  STATUS: $($err.Exception.Response.StatusCode)" -ForegroundColor Yellow
    Write-Host $err.Exception.Message -ForegroundColor Red
    Write-Host "`n  Common fixes:" -ForegroundColor Cyan
    Write-Host "  - Caller needs role: Authentication Policy Administrator (or higher)" -ForegroundColor Yellow
    Write-Host "  - Confirm tenant is an External ID (CIAM) tenant" -ForegroundColor Yellow
    exit 1
}

# ─── VERIFY ───
Write-Host "`n  Verifying..." -ForegroundColor Cyan
$verify = $null
for ($attempt = 1; $attempt -le 5; $attempt++) {
    Start-Sleep -Seconds $attempt
    try {
        $verify = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email"
        if ($verify.state -eq "enabled" -and $verify.allowExternalIdToUseEmailOtp -eq "enabled") {
            break
        }
    } catch {
        if ($attempt -eq 5) { throw }
    }
}
if ($verify.state -ne "enabled" -or $verify.allowExternalIdToUseEmailOtp -ne "enabled") {
    Write-Host "  Verification failed: Email OTP is not fully enabled for External ID." -ForegroundColor Red
    exit 1
}
Write-Host "  Email OTP state: $($verify.state)" -ForegroundColor Green
Write-Host "  External ID use: $($verify.allowExternalIdToUseEmailOtp)" -ForegroundColor Green

Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Email OTP is now enabled for this tenant." -ForegroundColor Green
Write-Host "  Users can verify their email with a one-time passcode." -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
