# ═══════════════════════════════════════════════════════════════════
#  08 — Create Claims Mapping Policy (custom token claims)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Create a claims mapping policy and assign it to the
#           service principal so custom claims appear in the token.
#           This replaces B2C XML claims transformations with a
#           declarative JSON policy.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  What this does:
#    1. Creates a claims mapping policy with the configured claims
#    2. Enables acceptMappedClaims on the app registration
#    3. Assigns the policy to the service principal
#    4. Verifies the assignment
#
#  Chains from: .last-created-app.json (appId, spId, tenantId)
#
#  Run: pwsh ./08-claims-mapping-policy.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/6] Reading context from script 01..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing context file. Run script 01 first." -ForegroundColor Red
    exit 1
}
$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$tenantId   = $appContext.tenantId
$appId      = $appContext.appId
$appObjId   = if ($appContext.appObjectId) { $appContext.appObjectId } else { $appContext.objectId }
$spId       = if ($appContext.spId) { $appContext.spId } else { $appContext.servicePrincipalId }
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  App    : $appId" -ForegroundColor Gray
Write-Host "  App OID: $appObjId" -ForegroundColor Gray
Write-Host "  SP     : $spId" -ForegroundColor Gray

if (-not $appObjId) {
    Write-Host "  ERROR: No app object ID in context. Re-run script 01." -ForegroundColor Red
    exit 1
}
if (-not $spId) {
    Write-Host "  WARNING: No SP ID in context. Looking it up..." -ForegroundColor Yellow
    try {
        $spFilter = "appId eq '$appId'"
        $sps = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/servicePrincipals?`$filter=$spFilter"
        if ($sps.value -and $sps.value.Count -gt 0) {
            $spId = $sps.value[0].id
            Write-Host "  Found SP: $spId" -ForegroundColor Green
        } else {
            Write-Host "  No SP found. Creating one..." -ForegroundColor Yellow
            $spBody = @{ appId = $appId } | ConvertTo-Json
            $sp = Invoke-MgGraphRequest -Method POST `
                -Uri "https://graph.microsoft.com/v1.0/servicePrincipals" `
                -Body $spBody -ContentType "application/json"
            $spId = $sp.id
            Write-Host "  Created SP: $spId" -ForegroundColor Green
        }
    } catch {
        Write-Host "  FAILED to find/create SP: $_" -ForegroundColor Red
        exit 1
    }
}

# ─── CONFIG (edit these to customize your token claims) ───
# Each entry maps a source claim to a JWT claim name in the token.
# Source options: "user" (directory attribute), "application", "company"
# Common examples:
#   - User's display name     → Source: "user", ID: "displayname", JwtClaimType: "name"
#   - User's email            → Source: "user", ID: "mail", JwtClaimType: "email"
#   - User's department       → Source: "user", ID: "department", JwtClaimType: "dept"
#   - Extension attribute     → Source: "user", ID: "extension_<appId>_fieldname", JwtClaimType: "custom_field"
#
# These claims were detected from the source B2C policy: {{POLICY_NAME}}
$policyDisplayName = "{{FLOW_NAME}}-claims-mapping"
$claimsSchema = @(
{{CLAIMS_SCHEMA_BLOCK}}
)

# ─── CONNECT ───
Write-Host "`n[2/6] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "Policy.ReadWrite.ApplicationConfiguration","Application.ReadWrite.All" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── BUILD CLAIMS MAPPING POLICY DEFINITION ───
Write-Host "`n[3/6] Creating claims mapping policy..." -ForegroundColor Cyan

# Build the ClaimsSchema array for the policy definition JSON
$schemaEntries = $claimsSchema | ForEach-Object {
    $entry = @{ Source = $_.Source; ID = $_.ID; JwtClaimType = $_.JwtClaimType }
    $entry
}

$policyDefinition = @{
    ClaimsMappingPolicy = @{
        Version = 1
        IncludeBasicClaimSet = "true"
        ClaimsSchema = $schemaEntries
    }
} | ConvertTo-Json -Depth 10 -Compress

Write-Host "  Policy definition:" -ForegroundColor Gray
Write-Host "  $policyDefinition" -ForegroundColor DarkGray

$policyBody = @{
    definition = @($policyDefinition)
    displayName = $policyDisplayName
    isOrganizationDefault = $false
} | ConvertTo-Json -Depth 5

try {
    $existing = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies"
    $policy = $existing.value | Where-Object { $_.displayName -eq $policyDisplayName } | Select-Object -First 1

    if ($policy) {
        $policyId = $policy.id
        $currentPolicy = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/$policyId"
        $currentDefinition = @($currentPolicy.definition)[0]
        if ($currentDefinition -ne $policyDefinition) {
            Invoke-MgGraphRequest -Method PATCH `
                -Uri "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/$policyId" `
                -Body $policyBody `
                -ContentType "application/json" | Out-Null
            Write-Host "  Updated existing policy definition: $policyId" -ForegroundColor Green
        } else {
            Write-Host "  Existing policy already matches: $policyId" -ForegroundColor Yellow
        }
    } else {
        $policy = Invoke-MgGraphRequest -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies" `
            -Body $policyBody `
            -ContentType "application/json"
        $policyId = $policy.id
        Write-Host "  Created policy: $policyId" -ForegroundColor Green
    }
    Write-Host "  Display name : $policyDisplayName" -ForegroundColor Gray
} catch {
    Write-Host "  FAILED to create or update policy" -ForegroundColor Red
    Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ─── ENABLE acceptMappedClaims ON THE APP ───
Write-Host "`n[4/6] Enabling acceptMappedClaims on the application..." -ForegroundColor Cyan
try {
    $appPatchBody = @{
        api = @{
            acceptMappedClaims = $true
        }
    } | ConvertTo-Json -Depth 5

    Invoke-MgGraphRequest -Method PATCH `
        -Uri "https://graph.microsoft.com/v1.0/applications/$appObjId" `
        -Body $appPatchBody `
        -ContentType "application/json"

    Write-Host "  acceptMappedClaims enabled." -ForegroundColor Green
    Write-Host "  This generated app is single-tenant, so acceptMappedClaims=true is supported." -ForegroundColor Green
    Write-Host "  Do not use acceptMappedClaims=true on a multitenant app; that case requires a custom signing key." -ForegroundColor Yellow
} catch {
    Write-Host "  FAILED to set acceptMappedClaims: $_" -ForegroundColor Red
    Write-Host "  The claims policy would not be reliable without this app setting." -ForegroundColor Yellow
    exit 1
}

# ─── ASSIGN POLICY TO SERVICE PRINCIPAL ───
Write-Host "`n[5/6] Assigning claims mapping policy to service principal..." -ForegroundColor Cyan
$assignBody = @{
    "@odata.id" = "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/$policyId"
} | ConvertTo-Json

try {
    Invoke-MgGraphRequest -Method POST `
        -Uri "https://graph.microsoft.com/v1.0/servicePrincipals/$spId/claimsMappingPolicies/`$ref" `
        -Body $assignBody `
        -ContentType "application/json"

    Write-Host "  Policy assigned to SP successfully!" -ForegroundColor Green
} catch {
    $err = $_
    if ($err.Exception.Message -like "*already exist*") {
        Write-Host "  Policy is already assigned to this SP." -ForegroundColor Yellow
    } else {
        Write-Host "  FAILED to assign policy" -ForegroundColor Red
        Write-Host "  $($err.Exception.Message)" -ForegroundColor Red
        exit 1
    }
}

# ─── VERIFY ───
Write-Host "`n[6/6] Verifying..." -ForegroundColor Cyan
# Primary check: confirm the policy exists (covered by the ApplicationConfiguration scope)
try {
    $policyCheck = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/claimsMappingPolicies/$policyId"
    Write-Host "  Policy exists: $($policyCheck.displayName) ($($policyCheck.id))" -ForegroundColor Green
} catch {
    Write-Host "  WARNING: could not read back policy ${policyId}: $($_.Exception.Message)" -ForegroundColor Yellow
}
# Secondary check: confirm the SP assignment (needs Policy.Read.All)
try {
    $assigned = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/servicePrincipals/$spId/claimsMappingPolicies"
    $count = ($assigned.value | Measure-Object).Count
    Write-Host "  SP has $count claims mapping policy(ies) assigned." -ForegroundColor Green
    foreach ($p in $assigned.value) {
        Write-Host "    - $($p.displayName) ($($p.id))" -ForegroundColor Gray
    }
} catch {
    Write-Host "  Note: could not read SP assignment (needs Policy.Read.All role/scope)." -ForegroundColor Yellow
    Write-Host "  The assignment POST above returned success." -ForegroundColor Gray
}

# ─── SAVE CONTEXT ───
$claimsCtx = @{
    policyId = $policyId
    policyDisplayName = $policyDisplayName
    claimsConfigured = ($claimsSchema | ForEach-Object { $_.JwtClaimType }) -join ", "
    assignedToSpId = $spId
} | ConvertTo-Json
$claimsCtx | Out-File "$PSScriptRoot\.last-claims-policy.json" -Encoding UTF8
Write-Host "`n  Context saved to .last-claims-policy.json" -ForegroundColor Gray

Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Claims mapping policy configured!" -ForegroundColor Green
Write-Host "  Custom claims in token: $( ($claimsSchema | ForEach-Object { $_.JwtClaimType }) -join ', ' )" -ForegroundColor White
Write-Host "" -ForegroundColor White
Write-Host "  acceptMappedClaims note:" -ForegroundColor Yellow
Write-Host "    This package creates a single-tenant app, where acceptMappedClaims=true is supported." -ForegroundColor Gray
Write-Host "    For a multitenant app, leave acceptMappedClaims disabled and use a custom signing key." -ForegroundColor Gray
Write-Host "" -ForegroundColor White
Write-Host "  To verify end-to-end: sign in, decode the token at https://jwt.ms," -ForegroundColor White
Write-Host "  and confirm the mapped claims appear." -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
