# ═══════════════════════════════════════════════════════════════════
#  09 — Enable Self-Service Password Reset (SSPR)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Enable SSPR so users can reset their own password
#           without admin intervention. In B2C this was a separate
#           PasswordReset policy/journey; in External ID it's a
#           tenant-level setting on the user flow.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  What this does:
#    1. Verifies the user flow exists (SSPR needs an email+password flow)
#    2. Ensures Email OTP is enabled (the password-reset verification method)
#    3. Documents optional SMS reset (script 11) and the branding link toggle
#
#  Note: External ID has no flow-level SSPR toggle and no "Password" auth
#        method to enable. SSPR works once the flow is email+password and
#        Email OTP (or SMS) is enabled. The "Forgot password?" link shows by
#        default and can be hidden/customized only via Company Branding.
#
#  Chains from: .last-created-app.json, .last-created-flow.json
#
#  Run: pwsh ./09-enable-sspr.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT ───
Write-Host "`n[1/5] Reading context from previous scripts..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
$flowCtx = "$PSScriptRoot\.last-created-flow.json"

if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing .last-created-app.json. Run script 01 first." -ForegroundColor Red
    exit 1
}
if (-not (Test-Path $flowCtx)) {
    Write-Host "  Missing .last-created-flow.json. Run script 02 first." -ForegroundColor Red
    exit 1
}

$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$flowContext = Get-Content $flowCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$flowId = $flowContext.flowId
Write-Host "  Tenant  : $tenantId" -ForegroundColor Gray
Write-Host "  Flow ID : $flowId" -ForegroundColor Gray

# ─── CONNECT ───
Write-Host "`n[2/5] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "EventListener.ReadWrite.All","Policy.ReadWrite.AuthenticationMethod" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── VERIFY THE USER FLOW (SSPR requires an email+password flow) ───
Write-Host "`n[3/5] Verifying the user flow..." -ForegroundColor Cyan

# External ID has NO flow-level SSPR toggle. SSPR is available whenever:
#   1. the user flow uses Email + Password (local accounts exist to reset)
#   2. a reset verification method (Email OTP / SMS) is enabled (next step)
#   3. (optional) the "Forgot password?" link is shown via Company Branding
try {
    $currentFlow = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow?`$expand=onAuthenticationMethodLoadStart"
    $flowAppIds = @($currentFlow.conditions.applications.includeApplications | ForEach-Object { $_.appId })
    $flowProviderIds = @($currentFlow.onAuthenticationMethodLoadStart.identityProviders | ForEach-Object { $_.id })
    if ($flowAppIds -notcontains $appContext.appId) {
        throw "The target application is not bound to this user flow."
    }
    if ($flowProviderIds -notcontains "EmailPassword-OAUTH") {
        throw "The user flow does not use Email + Password as its local-account provider."
    }
    Write-Host "  Flow found: $($currentFlow.displayName)" -ForegroundColor Green
} catch {
    Write-Host "  Could not read flow: $_" -ForegroundColor Red
    exit 1
}

# ─── ENABLE EMAIL OTP (the password-reset verification method) ───
Write-Host "`n[4/5] Ensuring Email OTP is enabled (SSPR verification method)..." -ForegroundColor Cyan

# External ID has NO "Password" authentication method to toggle. SSPR identity
# verification uses Email OTP (and optionally SMS). We ensure Email OTP is on.
$emailBody = @{
    "@odata.type"                = "#microsoft.graph.emailAuthenticationMethodConfiguration"
    state                        = "enabled"
    allowExternalIdToUseEmailOtp = "enabled"
} | ConvertTo-Json -Depth 5

try {
    $currentEmail = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email"
    if ($currentEmail.state -eq "enabled" -and $currentEmail.allowExternalIdToUseEmailOtp -eq "enabled") {
        Write-Host "  Email OTP already enabled." -ForegroundColor Green
    } else {
        Invoke-MgGraphRequest -Method PATCH `
            -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email" `
            -Body $emailBody `
            -ContentType "application/json"
        $verifyEmail = $null
        for ($attempt = 1; $attempt -le 5; $attempt++) {
            Start-Sleep -Seconds $attempt
            try {
                $verifyEmail = Invoke-MgGraphRequest -Method GET `
                    -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Email"
                if ($verifyEmail.state -eq "enabled" -and $verifyEmail.allowExternalIdToUseEmailOtp -eq "enabled") {
                    break
                }
            } catch {
                if ($attempt -eq 5) { throw }
            }
        }
        if ($verifyEmail.state -ne "enabled" -or $verifyEmail.allowExternalIdToUseEmailOtp -ne "enabled") {
            throw "Email OTP verification failed: External ID use is not fully enabled."
        }
        Write-Host "  Email OTP enabled (state: $($verifyEmail.state))." -ForegroundColor Green
    }
} catch {
    $err = $_
    Write-Host "  FAILED to ensure Email OTP method." -ForegroundColor Red
    Write-Host "  STATUS: $($err.Exception.Response.StatusCode)" -ForegroundColor Yellow
    Write-Host "  $($err.Exception.Message)" -ForegroundColor Red
    Write-Host "  Fix: caller needs Authentication Policy Administrator; confirm CIAM tenant." -ForegroundColor Yellow
    exit 1
}

# ─── OPTIONAL RESET METHODS + LINK VISIBILITY ───
Write-Host "`n[5/5] Optional SSPR enhancements (no action required)..." -ForegroundColor Cyan
Write-Host "  - SMS reset: run script 11 to enable SMS as a reset/MFA method." -ForegroundColor Gray
Write-Host "    SMS is an add-on and needs the tenant linked to an Azure subscription." -ForegroundColor DarkGray
Write-Host "  - 'Forgot password?' link: shown by default. To hide, show, or" -ForegroundColor Gray
Write-Host "    customize it, use Company Branding -> Default sign-in -> Sign-in" -ForegroundColor Gray
Write-Host "    form -> Self-service password reset (portal-only setting)." -ForegroundColor DarkGray

# ─── SUMMARY ───
Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Self-Service Password Reset is ready." -ForegroundColor Green
Write-Host "" -ForegroundColor White
Write-Host "  How it works in External ID:" -ForegroundColor White
Write-Host "    - Users select 'Forgot password?' on the sign-in page" -ForegroundColor Gray
Write-Host "    - They verify via Email OTP (ensured above), then set a new password" -ForegroundColor Gray
Write-Host "" -ForegroundColor White
Write-Host "  B2C equivalent: B2C_1A_PasswordReset policy" -ForegroundColor Gray
Write-Host "  External ID:    Built into the sign-in experience (no separate flow)" -ForegroundColor Gray
Write-Host "" -ForegroundColor White
Write-Host "  To verify end-to-end:" -ForegroundColor White
Write-Host "    1. Open your app's sign-in page" -ForegroundColor Gray
Write-Host "    2. Enter an email, then select 'Forgot password?'" -ForegroundColor Gray
Write-Host "    3. Complete the Email OTP verification + new password" -ForegroundColor Gray
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
