# ═══════════════════════════════════════════════════════════════════
#  11 — Enable SMS One-Time Passcode (MFA) Authentication
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Enable SMS (text message) as a multi-factor authentication
#           method in the External ID tenant. In B2C, phone/SMS was a
#           sign-in or MFA option; in External ID, SMS is supported as a
#           SECOND FACTOR (MFA), not as a primary sign-in method.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  What this does:
#    - Enables the SMS authentication method at the tenant level
#    - Targets all users (all_users) so SMS is available as a 2nd factor
#
#  To actually REQUIRE MFA at sign-in, pair this with a Conditional
#  Access policy (script 12) whose grant control requires MFA.
#
#  Chains from: .last-created-app.json (for tenant context)
#
#  Run: pwsh ./11-enable-sms-mfa.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/4] Reading context from script 01..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing context file. Run script 01 first." -ForegroundColor Red
    exit 1
}
$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray

# ─── CONNECT ───
Write-Host "`n[2/4] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "Policy.ReadWrite.AuthenticationMethod" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── CHECK CURRENT STATUS (idempotent) ───
Write-Host "`n[3/4] Checking current SMS configuration..." -ForegroundColor Cyan
try {
    $currentConfig = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Sms"
    $currentState = $currentConfig.state
    Write-Host "  Current state: $currentState" -ForegroundColor Gray

    if ($currentState -eq "enabled") {
        Write-Host "  SMS is already enabled. No changes needed." -ForegroundColor Green
        Write-Host "  Follow-up: test with a user who has a registered phone method and confirm billing/telephony readiness." -ForegroundColor Yellow
        Write-Host "`n  Done!" -ForegroundColor Cyan
        exit 0
    }
} catch {
    Write-Host "  Could not read current config (may not exist yet). Proceeding..." -ForegroundColor Yellow
}

# ─── ENABLE SMS ───
Write-Host "`n[4/4] Enabling SMS authentication method..." -ForegroundColor Cyan
$body = @{
    "@odata.type"  = "#microsoft.graph.smsAuthenticationMethodConfiguration"
    state          = "enabled"
} | ConvertTo-Json -Depth 5

try {
    Invoke-MgGraphRequest -Method PATCH `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Sms" `
        -Body $body `
        -ContentType "application/json"

    Write-Host "  SMS enabled successfully!" -ForegroundColor Green
} catch {
    $err = $_
    Write-Host "  FAILED - see error below" -ForegroundColor Red
    Write-Host "  STATUS: $($err.Exception.Response.StatusCode)" -ForegroundColor Yellow
    if ($err.ErrorDetails.Message) { Write-Host "  BODY: $($err.ErrorDetails.Message)" -ForegroundColor Red }
    Write-Host "`n  Common fixes:" -ForegroundColor Cyan
    Write-Host "  - Caller needs role: Authentication Policy Administrator (or higher)" -ForegroundColor Yellow
    Write-Host "  - Confirm tenant is an External ID (CIAM) tenant" -ForegroundColor Yellow
    Write-Host "  - SMS may require a telephony/usage prerequisite on the tenant" -ForegroundColor Yellow
    Write-Host "  - Current v1.0 only documents state/excludeTargets as writable; configure targeting in the admin center if needed" -ForegroundColor Yellow
    exit 1
}

# ─── VERIFY ───
Write-Host "`n  Verifying..." -ForegroundColor Cyan
$verify = $null
for ($attempt = 1; $attempt -le 5; $attempt++) {
    Start-Sleep -Seconds $attempt
    try {
        $verify = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Sms"
        if ($verify.state -eq "enabled") { break }
    } catch {
        if ($attempt -eq 5) { throw }
    }
}
if (-not $verify -or $verify.state -ne "enabled") {
    Write-Host "  Verification failed: SMS is not enabled after the update." -ForegroundColor Red
    exit 1
}
Write-Host "  SMS state: $($verify.state)" -ForegroundColor Green

Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  SMS is now enabled as an MFA method for this tenant." -ForegroundColor Green
Write-Host "  Follow-up: confirm tenant billing/telephony readiness and test with a user who has a registered phone method." -ForegroundColor Yellow
Write-Host "  {{NEXT_STEP}}" -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
