# ═══════════════════════════════════════════════════════════════════
#  12 — Create Conditional Access Policy (Require MFA)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Translate a B2C "require MFA" / step-up requirement into an
#           External ID Conditional Access (CA) policy that requires
#           multi-factor authentication for the protected resource/API.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  SAFETY: This policy is created in REPORT-ONLY mode
#      (enabledForReportingButNotEnforced) so it CANNOT lock anyone out.
#      It logs what WOULD happen without enforcing it. After you confirm
#      your users can complete MFA (script 07 email OTP and/or script 11
#      SMS), flip the policy to "On" in the Entra admin center:
#        Entra admin center -> Protection -> Conditional Access -> this policy
#        -> Enable policy = On.
#
#  What this does:
#    - Creates a CA policy requiring MFA, scoped to the configured resource
#    - Targets all users, in report-only mode
#
#  Chains from: .last-created-app.json (tenant id + app id)
#  Produces:    .last-created-ca-policy.json (policy id, displayName)
#
#  Run: pwsh ./12-create-ca-policy.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── HELPERS ───
function Test-CaLicensingError {
    # True when a Graph error means Conditional Access is not licensed on this
    # tenant (an External ID external tenant not linked to an Azure subscription).
    param($err)
    $msg = ""
    if ($err.ErrorDetails -and $err.ErrorDetails.Message) { $msg = $err.ErrorDetails.Message }
    elseif ($err.Exception -and $err.Exception.Message) { $msg = $err.Exception.Message }
    return ($msg -match "not licensed" -or $msg -match "license")
}

function Show-CaLicensingHelp {
    Write-Host "`n  -----------------------------------------------------------" -ForegroundColor Cyan
    Write-Host "  Conditional Access is not enabled on this tenant yet." -ForegroundColor Yellow
    Write-Host "  An External ID external tenant must be LINKED to an Azure" -ForegroundColor Yellow
    Write-Host "  subscription before Conditional Access can be used." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  To fix (about 10 minutes; first 50,000 MAU are free):" -ForegroundColor Cyan
    Write-Host "    1. Open https://entra.microsoft.com" -ForegroundColor Gray
    Write-Host "    2. Switch to this external tenant (top-right directory picker)." -ForegroundColor Gray
    Write-Host "    3. Go to Home, then Billing (or Settings)." -ForegroundColor Gray
    Write-Host "    4. Choose 'Click here to upgrade' and add an Azure subscription." -ForegroundColor Gray
    Write-Host "    5. Re-run this script:  pwsh ./12-create-ca-policy.ps1" -ForegroundColor Gray
    Write-Host "  -----------------------------------------------------------`n" -ForegroundColor Cyan
}

function Test-IsEmptyConditionValue {
    param($Value)
    if ($null -eq $Value) { return $true }
    if ($Value -is [string]) { return [string]::IsNullOrWhiteSpace($Value) }
    if ($Value -is [System.Collections.IDictionary]) {
        foreach ($item in $Value.Values) {
            if (-not (Test-IsEmptyConditionValue $item)) { return $false }
        }
        return $true
    }
    if ($Value -is [System.Collections.IEnumerable]) {
        foreach ($item in $Value) {
            if (-not (Test-IsEmptyConditionValue $item)) { return $false }
        }
        return $true
    }
    $properties = @($Value.PSObject.Properties)
    if ($properties.Count -gt 0) {
        foreach ($property in $properties) {
            if (-not (Test-IsEmptyConditionValue $property.Value)) { return $false }
        }
        return $true
    }
    return $false
}

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/5] Reading context from script 01..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing context file. Run script 01 first." -ForegroundColor Red
    exit 1
}
$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$appId    = $appContext.appId
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  App    : $appId" -ForegroundColor Gray

$caDisplayName = "Require MFA - migrated from {{POLICY_NAME}}"
$caResourceAppId = "{{CA_RESOURCE_APP_ID}}"

if ($caResourceAppId -like "*EDIT_ME*") {
    Write-Host "`n  CONFIG REQUIRED - set `$caResourceAppId to the application ID of the protected API/resource." -ForegroundColor Yellow
    Write-Host "  Conditional Access evaluates resources, not the public/native client by default." -ForegroundColor Yellow
    exit 2
}

# ─── CONNECT ───
Write-Host "`n[2/5] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "Policy.Read.All","Policy.ReadWrite.ConditionalAccess" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── CHECK FOR EXISTING POLICY (idempotent) ───
Write-Host "`n[3/5] Checking for an existing CA policy named '$caDisplayName'..." -ForegroundColor Cyan
try {
    $existing = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies"
    $caPolicy = $existing.value | Where-Object { $_.displayName -eq $caDisplayName } | Select-Object -First 1

    if ($caPolicy) {
        Write-Host "  CA policy already exists - reusing." -ForegroundColor Yellow
        Write-Host "    id    : $($caPolicy.id)" -ForegroundColor Gray
        Write-Host "    state : $($caPolicy.state)" -ForegroundColor Gray
        $targets = @($caPolicy.conditions.applications.includeApplications)
        $excludedTargets = @($caPolicy.conditions.applications.excludeApplications)
        $includedUserActions = @($caPolicy.conditions.applications.includeUserActions)
        $includedAuthContexts = @($caPolicy.conditions.applications.includeAuthenticationContextClassReferences)
        $applicationFilter = $caPolicy.conditions.applications.applicationFilter
        $includedUsers = @($caPolicy.conditions.users.includeUsers)
        $excludedUsers = @($caPolicy.conditions.users.excludeUsers)
        $includedGroups = @($caPolicy.conditions.users.includeGroups)
        $excludedGroups = @($caPolicy.conditions.users.excludeGroups)
        $includedRoles = @($caPolicy.conditions.users.includeRoles)
        $excludedRoles = @($caPolicy.conditions.users.excludeRoles)
        $includeGuests = $caPolicy.conditions.users.includeGuestsOrExternalUsers
        $excludeGuests = $caPolicy.conditions.users.excludeGuestsOrExternalUsers
        $controls = @($caPolicy.grantControls.builtInControls)
        $clientAppTypes = @($caPolicy.conditions.clientAppTypes)
        $allowedConditionNames = @("applications", "users", "clientAppTypes")
        $hasExtraConditions = @(
            $caPolicy.conditions.PSObject.Properties |
                Where-Object {
                    $allowedConditionNames -notcontains $_.Name -and
                    -not (Test-IsEmptyConditionValue $_.Value)
                }
        ).Count -gt 0
        $hasExtraGrantControls = `
            @($caPolicy.grantControls.customAuthenticationFactors).Count -gt 0 -or `
            @($caPolicy.grantControls.termsOfUse).Count -gt 0 -or `
            $null -ne $caPolicy.grantControls.authenticationStrength
        $hasSessionControls = $null -ne $caPolicy.sessionControls -and `
            @($caPolicy.sessionControls.PSObject.Properties | Where-Object { $null -ne $_.Value }).Count -gt 0
        $configurationMatches = `
            $targets.Count -eq 1 -and $targets[0] -eq $caResourceAppId -and `
            $excludedTargets.Count -eq 0 -and `
            $includedUserActions.Count -eq 0 -and `
            $includedAuthContexts.Count -eq 0 -and `
            (Test-IsEmptyConditionValue $applicationFilter) -and `
            $includedUsers.Count -eq 1 -and $includedUsers[0] -eq "All" -and `
            $excludedUsers.Count -eq 0 -and `
            $includedGroups.Count -eq 0 -and $excludedGroups.Count -eq 0 -and `
            $includedRoles.Count -eq 0 -and $excludedRoles.Count -eq 0 -and `
            $null -eq $includeGuests -and $null -eq $excludeGuests -and `
            $controls.Count -eq 1 -and $controls[0] -eq "mfa" -and `
            $caPolicy.grantControls.operator -eq "OR" -and `
            ($clientAppTypes.Count -eq 0 -or ($clientAppTypes.Count -eq 1 -and $clientAppTypes[0] -eq "all")) -and `
            -not $hasExtraConditions -and `
            -not $hasExtraGrantControls -and `
            -not $hasSessionControls
        if (-not $configurationMatches) {
            Write-Host "  Existing same-name policy does not exactly match the requested all-user/resource/MFA controls." -ForegroundColor Red
            Write-Host "  It was left unchanged for safety. Rename it or choose a different generated policy name." -ForegroundColor Yellow
            exit 1
        }
        if ($caPolicy.state -ne "enabledForReportingButNotEnforced") {
            Write-Host "  Existing matching policy is '$($caPolicy.state)', not report-only." -ForegroundColor Red
            Write-Host "  It was left unchanged. Review its impact or return it to report-only before continuing." -ForegroundColor Yellow
            exit 1
        }
    }
} catch {
    if (Test-CaLicensingError $_) {
        Write-Host "  Conditional Access is not available on this tenant." -ForegroundColor Red
        Show-CaLicensingHelp
        exit 1
    }
    Write-Host "  Could not list existing policies. Proceeding to create..." -ForegroundColor Yellow
    $caPolicy = $null
}

# ─── CREATE CA POLICY (report-only) ───
if (-not $caPolicy) {
    Write-Host "`n[4/5] Creating CA policy (report-only) requiring MFA..." -ForegroundColor Cyan
    $policyBody = @{
        displayName = $caDisplayName
        state       = "enabledForReportingButNotEnforced"
        conditions  = @{
            applications = @{
                includeApplications = @($caResourceAppId)
            }
            users = @{
                includeUsers = @("All")
            }
        }
        grantControls = @{
            operator        = "OR"
            builtInControls = @("mfa")
        }
    } | ConvertTo-Json -Depth 10

    Write-Host "  Request body:" -ForegroundColor Gray
    Write-Host $policyBody -ForegroundColor Gray

    try {
        $caPolicy = Invoke-MgGraphRequest -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies" `
            -Body $policyBody `
            -ContentType "application/json"

        Write-Host "  Created." -ForegroundColor Green
        Write-Host "    id    : $($caPolicy.id)" -ForegroundColor White
        Write-Host "    state : $($caPolicy.state)" -ForegroundColor White
    } catch {
        $err = $_
        Write-Host "  FAILED to create CA policy" -ForegroundColor Red
        Write-Host "  STATUS: $($err.Exception.Response.StatusCode)" -ForegroundColor Yellow
        if ($err.ErrorDetails.Message) { Write-Host "  BODY: $($err.ErrorDetails.Message)" -ForegroundColor Red }
        if (Test-CaLicensingError $err) {
            Show-CaLicensingHelp
        } else {
            Write-Host "`n  Common fixes:" -ForegroundColor Cyan
            Write-Host "  - Caller needs role: Conditional Access Administrator or Security Administrator" -ForegroundColor Yellow
            Write-Host "  - Confirm `$caResourceAppId is the protected resource application ID in this tenant" -ForegroundColor Yellow
        }
        exit 1
    }
}

# ─── VERIFY + SAVE CONTEXT ───
Write-Host "`n[5/5] Verifying..." -ForegroundColor Cyan
$verify = Invoke-MgGraphRequest -Method GET `
    -Uri "https://graph.microsoft.com/v1.0/identity/conditionalAccess/policies/$($caPolicy.id)"
Write-Host "  Policy '$($verify.displayName)' state: $($verify.state)" -ForegroundColor Green

$caContext = @{
    policyId    = $caPolicy.id
    displayName = $caDisplayName
    state       = $verify.state
    resourceAppId = $caResourceAppId
}
$caContext | ConvertTo-Json | Out-File "$PSScriptRoot\.last-created-ca-policy.json"
Write-Host "  Saved CA policy context to .last-created-ca-policy.json" -ForegroundColor Cyan

Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Conditional Access policy created in REPORT-ONLY mode." -ForegroundColor Green
Write-Host "  It is NOT enforced yet. Validate MFA works, then turn it" -ForegroundColor Yellow
Write-Host "      On in: Entra admin center -> Protection -> Conditional Access." -ForegroundColor Yellow
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
