# ═══════════════════════════════════════════════════════════════════
#  13 — Enable Passkey (FIDO2) Authentication
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Enable the tenant FIDO2/passkey policy. This is only the
#           policy portion of a passkey rollout.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  What this does:
#    - Enables the FIDO2/passkey authentication method at the tenant level
#    - Allows self-service passkey registration
#    - Preserves existing passkey profiles and user/group targeting
#
#  IMPORTANT: Policy enablement alone is not a complete passkey rollout.
#      Users need email/username + password local accounts and recent MFA.
#      External ID also requires Azure Front Door, a custom URL domain,
#      and a credential management experience for users to register/remove passkeys.
#      The application must be associated with a sign-up/sign-in user flow.
#      Passkeys use browser-delegated authentication and are not supported
#      through the native-auth APIs.
#
#  Chains from: .last-created-app.json (for tenant context)
#
#  Run: pwsh ./13-enable-passkey.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPT 01 ───
Write-Host "`n[1/4] Reading context from script 01..." -ForegroundColor Cyan
$appCtx = "$PSScriptRoot\.last-created-app.json"
if (-not (Test-Path $appCtx)) {
    Write-Host "  Missing context file. Run script 01 first." -ForegroundColor Red
    exit 1
}
$appContext = Get-Content $appCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray

# ─── CONNECT ───
Write-Host "`n[2/4] Connecting to Microsoft Graph..." -ForegroundColor Cyan
try {
    Connect-MgGraph -TenantId $tenantId -Scopes "Policy.ReadWrite.AuthenticationMethod" -NoWelcome -ErrorAction Stop
    Write-Host "  Connected." -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $_" -ForegroundColor Red
    exit 1
}

# ─── CHECK CURRENT STATUS (idempotent) ───
Write-Host "`n[3/4] Checking current passkey (FIDO2) configuration..." -ForegroundColor Cyan
try {
    $currentConfig = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Fido2"
    $currentState = $currentConfig.state
    Write-Host "  Current state: $currentState" -ForegroundColor Gray
    if ($currentState -eq "enabled" `
        -and $currentConfig.isSelfServiceRegistrationAllowed -eq $true) {
        Write-Host "  Passkey base policy already matches. No changes needed." -ForegroundColor Green
        Write-Host "  Policy Translator intentionally leaves passkey profiles and target assignments unchanged." -ForegroundColor Yellow
        Write-Host "  Follow-up: configure targeting/profiles, local password accounts, recent MFA, Azure Front Door, custom URL domain, and credential registration." -ForegroundColor Yellow
        Write-Host "`n  Done!" -ForegroundColor Cyan
        exit 0
    }
} catch {
    Write-Host "  Could not read current config (may not exist yet). Proceeding..." -ForegroundColor Yellow
}

# ─── ENABLE PASSKEY (FIDO2) ───
Write-Host "`n[4/4] Enabling passkey (FIDO2) authentication method..." -ForegroundColor Cyan
$body = @{
    "@odata.type"                    = "#microsoft.graph.fido2AuthenticationMethodConfiguration"
    state                            = "enabled"
    isSelfServiceRegistrationAllowed = $true
} | ConvertTo-Json -Depth 5

try {
    Invoke-MgGraphRequest -Method PATCH `
        -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Fido2" `
        -Body $body `
        -ContentType "application/json"

    Write-Host "  Passkey (FIDO2) enabled successfully!" -ForegroundColor Green
} catch {
    $err = $_
    Write-Host "  FAILED - see error below" -ForegroundColor Red
    Write-Host "  STATUS: $($err.Exception.Response.StatusCode)" -ForegroundColor Yellow
    if ($err.ErrorDetails.Message) { Write-Host "  BODY: $($err.ErrorDetails.Message)" -ForegroundColor Red }
    Write-Host "`n  Common fixes:" -ForegroundColor Cyan
    Write-Host "  - Caller needs role: Authentication Policy Administrator (or higher)" -ForegroundColor Yellow
    Write-Host "  - Confirm tenant is an External ID (CIAM) tenant" -ForegroundColor Yellow
    Write-Host "  - Confirm Azure Front Door and a custom URL domain are configured for the external tenant" -ForegroundColor Yellow
    exit 1
}

# ─── VERIFY ───
Write-Host "`n  Verifying..." -ForegroundColor Cyan
$verify = $null
for ($attempt = 1; $attempt -le 5; $attempt++) {
    Start-Sleep -Seconds $attempt
    try {
        $verify = Invoke-MgGraphRequest -Method GET `
            -Uri "https://graph.microsoft.com/v1.0/policies/authenticationMethodsPolicy/authenticationMethodConfigurations/Fido2"
        if ($verify.state -eq "enabled" -and $verify.isSelfServiceRegistrationAllowed -eq $true) {
            break
        }
    } catch {
        if ($attempt -eq 5) { throw }
    }
}
if ($verify.state -ne "enabled" `
    -or $verify.isSelfServiceRegistrationAllowed -ne $true) {
    Write-Host "  Verification failed: the FIDO2 base policy is not enabled for self-service registration." -ForegroundColor Red
    exit 1
}
Write-Host "  Passkey (FIDO2) state: $($verify.state)" -ForegroundColor Green

Write-Host "`n═══════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  The passkey (FIDO2) tenant policy is enabled." -ForegroundColor Green
Write-Host "  Policy Translator did not modify passkey profiles or target assignments." -ForegroundColor Yellow
Write-Host "  Follow-up: configure targeting/profiles, confirm local password accounts and recent MFA, then configure Azure Front Door, a custom URL domain, and passkey registration/removal." -ForegroundColor Yellow
Write-Host "  Passkeys are browser-delegated and are not supported through native-auth APIs." -ForegroundColor Yellow
Write-Host "  {{NEXT_STEP}}" -ForegroundColor White
Write-Host "═══════════════════════════════════════════════════════`n" -ForegroundColor Cyan
