# ═══════════════════════════════════════════════════════════════════
#  14 — Create Custom User Attributes (and add them to the sign-up flow)
# ═══════════════════════════════════════════════════════════════════
#
#  Purpose: Create the tenant custom (extension) user attributes that the
#           B2C policy collected at sign-up, then add them to the user
#           flow created by script 02 so they appear on the sign-up page
#           and are written to the directory.
#
#  Generated by Policy Translator
#  Source policy: {{POLICY_NAME}}
#  Generated at : {{GENERATED_AT}}
#
#  Chains from: .last-created-app.json (01) + .last-created-flow.json (02)
#  Produces:    .last-custom-attributes.json (name -> id map)
#
#  Run: pwsh ./14-create-custom-attributes.ps1
# ═══════════════════════════════════════════════════════════════════

# ─── READ CONTEXT FROM SCRIPTS 01 + 02 ───
Write-Host "`n[1/6] Reading context from scripts 01 + 02..." -ForegroundColor Cyan
$appCtx  = "$PSScriptRoot\.last-created-app.json"
$flowCtx = "$PSScriptRoot\.last-created-flow.json"
if (-not (Test-Path $appCtx) -or -not (Test-Path $flowCtx)) {
    Write-Host "  Missing context files. Run scripts 01 and 02 first." -ForegroundColor Red
    exit 1
}
$appContext  = Get-Content $appCtx  -Raw | ConvertFrom-Json
$flowContext = Get-Content $flowCtx -Raw | ConvertFrom-Json
$tenantId = $appContext.tenantId
$flowId   = $flowContext.flowId
$flowName = $flowContext.flowName
Write-Host "  Tenant : $tenantId" -ForegroundColor Gray
Write-Host "  Flow   : $flowId ($flowName)" -ForegroundColor Gray

# ─── CONFIG (custom attributes derived from your policy) ───
$customAttributes = @(
{{CUSTOM_ATTRIBUTES_BLOCK}}
)

if ($customAttributes.Count -eq 0) {
    Write-Host "`n  No custom attributes to create. Nothing to do." -ForegroundColor Yellow
    exit 0
}

# ─── CONNECT ───
Write-Host "`n[2/6] Connecting to Microsoft Graph..." -ForegroundColor Cyan
Write-Host "  Scopes: IdentityUserFlow.ReadWrite.All, EventListener.ReadWrite.All" -ForegroundColor Gray
try {
    $context = Get-MgContext
    $needsReconnect = $true
    if ($context -and $context.TenantId -eq $tenantId `
        -and $context.Scopes -contains "IdentityUserFlow.ReadWrite.All" `
        -and $context.Scopes -contains "EventListener.ReadWrite.All") {
        $needsReconnect = $false
    }
    if ($needsReconnect) {
        Connect-MgGraph -TenantId $tenantId `
            -Scopes "IdentityUserFlow.ReadWrite.All","EventListener.ReadWrite.All" `
            -NoWelcome -ErrorAction Stop
    }
    Write-Host "  Connected to tenant: $tenantId" -ForegroundColor Green
} catch {
    Write-Host "  Connection failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

# ─── READ EXISTING CUSTOM ATTRIBUTES (idempotent) ───
Write-Host "`n[3/6] Reading existing user flow attributes..." -ForegroundColor Cyan
$existingAttrs = @()
try {
    $resp = Invoke-MgGraphRequest -Method GET `
        -Uri "https://graph.microsoft.com/v1.0/identity/userFlowAttributes"
    $existingAttrs = @($resp.value)
} catch {
    Write-Host "  Could not list attributes (non-blocking). Will attempt create." -ForegroundColor Yellow
}

# ─── CREATE EACH CUSTOM ATTRIBUTE (if missing) ───
Write-Host "`n[4/6] Ensuring $($customAttributes.Count) custom attribute(s) exist..." -ForegroundColor Cyan
$resolved = @()
foreach ($attr in $customAttributes) {
    $match = $existingAttrs | Where-Object {
        $_.userFlowAttributeType -eq "custom" -and (
            $_.displayName -eq $attr.displayName -or $_.id -like "extension_*_$($attr.name)"
        )
    } | Select-Object -First 1

    if ($match) {
        Write-Host "  '$($attr.displayName)' already exists -> $($match.id)" -ForegroundColor Yellow
        $resolved += @{ id = $match.id; displayName = $attr.displayName; dataType = $attr.dataType; required = $attr.required }
        continue
    }

    $createBody = @{
        displayName           = $attr.displayName
        description           = "$($attr.displayName) (migrated custom attribute)"
        dataType              = $attr.dataType
        userFlowAttributeType = "custom"
    } | ConvertTo-Json -Depth 5

    try {
        $created = Invoke-MgGraphRequest -Method POST `
            -Uri "https://graph.microsoft.com/v1.0/identity/userFlowAttributes" `
            -Body $createBody -ContentType "application/json"
        Write-Host "  Created '$($attr.displayName)' -> $($created.id)" -ForegroundColor Green
        $resolved += @{ id = $created.id; displayName = $attr.displayName; dataType = $attr.dataType; required = $attr.required }
    } catch {
        Write-Host "  FAILED to create '$($attr.displayName)'" -ForegroundColor Red
        Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        if ($_.ErrorDetails.Message) { Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red }
        Write-Host "  Needs scope IdentityUserFlow.ReadWrite.All and role External ID User Flow Administrator." -ForegroundColor Yellow
        exit 1
    }
}

# ─── READ CURRENT FLOW (to see which attributes are already collected) ───
Write-Host "`n[5/6] Adding custom attribute(s) to the sign-up flow..." -ForegroundColor Cyan
$flowUri = "https://graph.microsoft.com/v1.0/identity/authenticationEventsFlows/$flowId"
try {
    $flow = Invoke-MgGraphRequest -Method GET -Uri $flowUri
} catch {
    Write-Host "  FAILED to read flow $flowId" -ForegroundColor Red
    Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
    if ($_.ErrorDetails.Message) { Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red }
    exit 1
}

$existingAttrIds = @()
if ($flow.onAttributeCollection -and $flow.onAttributeCollection.attributes) {
    $existingAttrIds = @($flow.onAttributeCollection.attributes | ForEach-Object { $_.id })
}

# Add each attribute via the dedicated POST attributes reference endpoint. Attributes
# CANNOT be added to a flow's onAttributeCollection with a PATCH; you must POST an
# @odata.id reference here. This adds the attribute to both the attributes collection
# and the page views with default settings and returns 204 No Content.
$attrsRefUri = "$flowUri/microsoft.graph.externalUsersSelfServiceSignUpEventsFlow/onAttributeCollection/microsoft.graph.onAttributeCollectionExternalUsersSelfServiceSignUp/attributes/`$ref"
$addedCount = 0
foreach ($r in $resolved) {
    if ($existingAttrIds -contains $r.id) {
        Write-Host "  '$($r.displayName)' already on flow - skipping." -ForegroundColor Yellow
        continue
    }
    $refBody = @{ "@odata.id" = "https://graph.microsoft.com/v1.0/identity/userFlowAttributes/$($r.id)" } | ConvertTo-Json
    try {
        Invoke-MgGraphRequest -Method POST -Uri $attrsRefUri `
            -Body $refBody -ContentType "application/json" | Out-Null
        Write-Host "  Added '$($r.displayName)' to flow." -ForegroundColor Green
        $addedCount++
    } catch {
        Write-Host "  FAILED to add '$($r.displayName)' to flow" -ForegroundColor Red
        Write-Host "  STATUS: $($_.Exception.Response.StatusCode)" -ForegroundColor Red
        if ($_.ErrorDetails.Message) { Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red }
        Write-Host "  Needs scope EventListener.ReadWrite.All and role External ID User Flow Administrator." -ForegroundColor Yellow
        exit 1
    }
}

if ($addedCount -eq 0) {
    Write-Host "  All custom attributes are already on the flow." -ForegroundColor Green
}

# ─── CUSTOMIZE PAGE SETTINGS (mark required / write-to-directory) ───
# The POST above adds attributes with default page settings. If the policy marks any
# attribute as required, apply that by PATCHing the page views. When PATCHing views you
# must send the FULL inputs list, so we re-read the flow and echo every input back,
# adjusting only our attributes. A failure is fatal because the resulting flow
# would not match the source policy's required/write-to-directory behavior.
$requiredIds = @($resolved | Where-Object { $_.required } | ForEach-Object { $_.id })
if ($requiredIds.Count -gt 0) {
    Write-Host "`n[6/6] Applying required-field settings..." -ForegroundColor Cyan
    try {
        $flow2 = Invoke-MgGraphRequest -Method GET -Uri $flowUri
        $attrs2 = @()
        $inputs2 = @()
        if ($flow2.onAttributeCollection) {
            $attrs2 = @($flow2.onAttributeCollection.attributes)
            if ($flow2.onAttributeCollection.attributeCollectionPage -and $flow2.onAttributeCollection.attributeCollectionPage.views) {
                $inputs2 = @($flow2.onAttributeCollection.attributeCollectionPage.views[0].inputs)
            }
        }

        # Rebuild clean objects (avoid echoing read-only fields back).
        $rebuiltAttrs = @()
        foreach ($a in $attrs2) {
            $rebuiltAttrs += @{
                id                    = $a.id
                displayName           = $a.displayName
                userFlowAttributeType = $a.userFlowAttributeType
                dataType              = $a.dataType
            }
        }
        $rebuiltInputs = @()
        foreach ($i in $inputs2) {
            $isRequired = $i.required
            $writeDir   = $i.writeToDirectory
            if ($requiredIds -contains $i.attribute) {
                $isRequired = $true
                $writeDir   = $true
            }
            $rebuiltInputs += @{
                attribute        = $i.attribute
                label            = $i.label
                inputType        = $i.inputType
                hidden           = $i.hidden
                editable         = $i.editable
                writeToDirectory = $writeDir
                required         = $isRequired
            }
        }

        $patchBody = @{
            "@odata.type" = "#microsoft.graph.externalUsersSelfServiceSignUpEventsFlow"
            onAttributeCollection = @{
                "@odata.type" = "#microsoft.graph.onAttributeCollectionExternalUsersSelfServiceSignUp"
                attributes = $rebuiltAttrs
                attributeCollectionPage = @{
                    views = @(
                        @{ inputs = $rebuiltInputs }
                    )
                }
            }
        } | ConvertTo-Json -Depth 20

        Invoke-MgGraphRequest -Method PATCH -Uri $flowUri `
            -Body $patchBody -ContentType "application/json" | Out-Null
        Write-Host "  Applied required-field settings." -ForegroundColor Green
    } catch {
        Write-Host "  FAILED to apply required-field settings." -ForegroundColor Red
        if ($_.ErrorDetails.Message) { Write-Host "  BODY: $($_.ErrorDetails.Message)" -ForegroundColor Red }
        exit 1
    }
} else {
    Write-Host "`n[6/6] No extra field customization needed." -ForegroundColor Cyan
}

# ─── SAVE CONTEXT ───
$map = @{}
foreach ($r in $resolved) { $map[$r.displayName] = $r.id }
@{
    flowId     = $flowId
    tenantId   = $tenantId
    attributes = $map
    addedAt    = (Get-Date).ToString("o")
} | ConvertTo-Json -Depth 5 | Out-File "$PSScriptRoot\.last-custom-attributes.json"

Write-Host "`n  SUCCESS" -ForegroundColor Green
Write-Host "  ---------------------------------------" -ForegroundColor Green
Write-Host "  Custom attributes on flow: $flowName" -ForegroundColor White
foreach ($r in $resolved) {
    Write-Host "    $($r.displayName)  ->  $($r.id)" -ForegroundColor White
}
Write-Host "  ---------------------------------------" -ForegroundColor Green

Write-Host "`nNEXT STEPS:" -ForegroundColor Yellow
Write-Host "  1. Open Entra admin center -> External Identities -> Custom user attributes to verify." -ForegroundColor White
Write-Host "  2. {{NEXT_STEP}}" -ForegroundColor White
