/**
 * Policy Translator — Main Entry Point
 *
 * Takes Analyzer JSON → produces migration package (scripts + gap report + README).
 * Simple. No auth ceremony. Just conversion.
 */

import fs from "fs";
import path from "path";
import { mapAllFeatures } from "./mappers/featureMap";
import { generatePackage, TenantConfig } from "./generators/scriptGenerator";
import { AnalysisFeature } from "./types";
import { extractPolicyContext, PolicyContext } from "./parsers/policyContextParser";
import { validateAndNormalize, printValidationReport } from "./parsers/inputValidator";

// --- Config ---
const INPUT_FILE = process.argv[2] || "src/fixtures/changePassword-analysis.json";
const OUTPUT_DIR = "output";

// --- Load ---
console.log(`\n📄 Loading: ${INPUT_FILE}`);
const rawJson = JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8"));

// --- Validate & Normalize (deterministic safety layer) ---
console.log(`\n🔎 Validating input...`);
const validation = validateAndNormalize(rawJson);
printValidationReport(validation);

if (!validation.valid) {
  console.error(`\n💥 Cannot proceed. Fix the validation errors above.`);
  process.exit(1);
}

const policyName: string = validation.policyName;
const features: AnalysisFeature[] = validation.features;

console.log(`\n📊 Policy: ${policyName}`);
console.log(`   Features: ${features.length}`);
console.log(`   Available: ${features.filter(f => f.externalIdAvailability === "Available").length}`);
console.log(`   Needs work: ${features.filter(f => f.externalIdAvailability !== "Available").length}`);

// --- Extract policy-specific context ---
const policyContext = extractPolicyContext(policyName, features);
console.log(`\n🔍 Extracted policy context:`);
console.log(`   App name: ${policyContext.appName}`);
console.log(`   Flow name: ${policyContext.flowName}`);
console.log(`   Claims: ${policyContext.claims.length} detected`);
console.log(`   Attributes: ${policyContext.attributes.length} detected`);
if (policyContext.idpDisplayNames.google) console.log(`   Google IdP: "${policyContext.idpDisplayNames.google}"`);
if (policyContext.idpDisplayNames.facebook) console.log(`   Facebook IdP: "${policyContext.idpDisplayNames.facebook}"`);
if (policyContext.idpDisplayNames.oidc) console.log(`   OIDC IdP: "${policyContext.idpDisplayNames.oidc}"`);

// Build tenant config with policy-derived values
const tenantConfig: TenantConfig = {
  tenantId: "<EDIT_ME_TENANT_ID>",
  appName: policyContext.appName,
  bundleId: "com.contoso.yourapp",
  flowName: policyContext.flowName,
  flowDescription: `Migrated from ${policyName} (generated by policy-translator)`,
  googleClientId: "<EDIT_ME_GOOGLE_CLIENT_ID>",
  googleClientSecret: "<EDIT_ME_GOOGLE_CLIENT_SECRET>",
  googleIdpDisplayName: policyContext.idpDisplayNames.google || "Login with Google",
  facebookAppId: "<EDIT_ME_FACEBOOK_APP_ID>",
  facebookAppSecret: "<EDIT_ME_FACEBOOK_APP_SECRET>",
  facebookIdpDisplayName: policyContext.idpDisplayNames.facebook || "Login with Facebook",
  caResourceAppId: "<EDIT_ME_CA_RESOURCE_APP_ID>",
};

// --- Map ---
console.log(`\n🔄 Mapping features to External ID...`);
const { mapped, unmapped } = mapAllFeatures(features);

console.log(`   ✅ Mapped: ${mapped.length}`);
if (unmapped.length > 0) {
  console.log(`   ⚠️  Unmapped: ${unmapped.join(", ")}`);
}

// --- Generate ---
console.log(`\n⚙️  Generating migration package...`);
const output = generatePackage(policyName, mapped, tenantConfig, policyContext);

// --- Write ---
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Write scripts
for (const script of output.scripts) {
  const filePath = path.join(OUTPUT_DIR, script.filename);
  fs.writeFileSync(filePath, script.content);
  console.log(`   📝 ${filePath}`);
}

// Write gap report
if (output.gapReport) {
  const gapPath = path.join(OUTPUT_DIR, "gap-report.md");
  fs.writeFileSync(gapPath, output.gapReport);
  console.log(`   📝 ${gapPath}`);
}

// Write README
const readmePath = path.join(OUTPUT_DIR, "README.md");
fs.writeFileSync(readmePath, output.readme);
console.log(`   📝 ${readmePath}`);

// --- Summary ---
console.log(`\n✅ Done! Migration package generated in ./${OUTPUT_DIR}/`);
console.log(`   ${output.scripts.length} script(s) + ${output.gapReport ? "1 gap report + " : ""}1 README`);
console.log(`\n   Next: edit the CONFIG block in ${OUTPUT_DIR}/01-create-native-app.ps1, then run the scripts in order.\n`);
